import type { CultureYearInput } from "@/lib/content/schema";

/** 2010 — CULTURAL CONTEXT (general history, not personal). */
export const culture2010: CultureYearInput = {
  year: 2010,
  headline: "A tablet, a camera app, and a lot of birds.",
  blurb:
    "The iPad arrived in April and the iPhone 4 in June, Instagram launched in October, and Kinect let you play with no controller at all. Angry Birds and Minecraft's beta turned phones and PCs into playgrounds, and Toy Story 3 and Inception ruled the summer.",
  design:
    "Peak skeuomorphism: leather calendars, linen backgrounds, wooden bookshelves. iOS 4's home screen folders and the iPad's stitched textures.",
  internet: [
    { label: "Instagram launches", kind: "app", icon: "camera", note: "October 6; filters and square photos." },
    { label: "Pinterest (beta)", kind: "site", icon: "pin" },
    { label: "Old Spice: The Man Your Man Could Smell Like", kind: "meme", icon: "video", note: "Personalised video replies on YouTube." },
    { label: "Double Rainbow", kind: "meme", icon: "video" },
    { label: "Bed Intruder Song", kind: "meme", icon: "music", note: "The Auto-Tune the News era." },
    { label: "Chatroulette", kind: "site", icon: "video" },
    { label: "Quora and Foursquare check-ins", kind: "app", icon: "pin" },
    { label: "Netflix streaming takes off", kind: "site", icon: "stream", note: "Streaming-only plans arrived in November." },
  ],
  tech: [
    { label: "iPad", kind: "device", icon: "tablet", note: "April 3; \"a magical and revolutionary device\"." },
    { label: "iPhone 4", kind: "phone", icon: "iphone", note: "Retina display, FaceTime, glass on both sides." },
    { label: "Kinect", kind: "console", icon: "xbox", note: "\"You are the controller.\"" },
    { label: "Xbox 360 S", kind: "console", icon: "xbox" },
    { label: "Samsung Galaxy S", kind: "phone", icon: "phone" },
    { label: "Nintendo Wii at its peak", kind: "console", icon: "wii" },
    { label: "MacBook Air redesign", kind: "computer", icon: "laptop", note: "11-inch and 13-inch, flash storage." },
    { label: "Beats by Dre", kind: "device", icon: "headphones", note: "Big headphones as a fashion statement." },
  ],
  games: [
    { label: "Angry Birds mania", kind: "game", icon: "iphone" },
    { label: "Minecraft (alpha and beta)", kind: "game", icon: "lego", note: "Word of mouth turned it into a phenomenon by year's end." },
    { label: "Cut the Rope and Fruit Ninja", kind: "game", icon: "iphone" },
    { label: "Super Mario Galaxy 2", kind: "game", icon: "wii" },
    { label: "Pokémon HeartGold and SoulSilver (US)", kind: "game", icon: "ds", note: "With the Pokéwalker pedometer." },
    { label: "Red Dead Redemption", kind: "game", icon: "xbox" },
    { label: "Halo: Reach and Call of Duty: Black Ops", kind: "game", icon: "xbox" },
    { label: "Just Dance 2 and Kinect Sports", kind: "game", icon: "wii" },
    { label: "Donkey Kong Country Returns", kind: "game", icon: "wii" },
  ],
  onScreen: [
    { label: "Toy Story 3", kind: "movie", icon: "toy" },
    { label: "Inception", kind: "movie", icon: "film" },
    { label: "Despicable Me", kind: "movie", icon: "film" },
    { label: "How to Train Your Dragon", kind: "movie", icon: "film" },
    { label: "Harry Potter and the Deathly Hallows: Part 1", kind: "movie", icon: "film" },
    { label: "Tangled", kind: "movie", icon: "film" },
    { label: "Adventure Time and Regular Show premiere", kind: "show", icon: "tv" },
    { label: "Victorious and Good Luck Charlie premiere", kind: "show", icon: "tv" },
    { label: "The Walking Dead premieres", kind: "show", icon: "tv" },
  ],
  music: [
    { id: "c2010-tiktok", title: "TiK ToK", artist: "Kesha" },
    { id: "c2010-baby", title: "Baby", artist: "Justin Bieber ft. Ludacris" },
    { id: "c2010-californiagurls", title: "California Gurls", artist: "Katy Perry ft. Snoop Dogg" },
    { id: "c2010-dynamite", title: "Dynamite", artist: "Taio Cruz" },
    { id: "c2010-lovetheway", title: "Love the Way You Lie", artist: "Eminem ft. Rihanna" },
    { id: "c2010-likeag6", title: "Like a G6", artist: "Far East Movement" },
    { id: "c2010-firework", title: "Firework", artist: "Katy Perry" },
  ],
  culture: [
    { label: "Silly Bandz", kind: "toy", icon: "toy", note: "Shaped rubber bands, traded and banned in classrooms." },
    { label: "Bieber Fever", kind: "trend", icon: "music" },
    { label: "Vuvuzelas", kind: "event", icon: "trophy", note: "South Africa World Cup." },
    { label: "Toms shoes", kind: "fashion", icon: "star" },
    { label: "\"Epic\" and \"Fail\"", kind: "slang", icon: "smile" },
    { label: "Planking begins", kind: "trend", icon: "smile", note: "It peaked in 2011." },
    { label: "Glee covers on repeat", kind: "trend", icon: "mic" },
  ],
  capsule: [
    { label: "iPad", icon: "tablet" },
    { label: "Instagram filter", icon: "camera" },
    { label: "Kinect", icon: "xbox" },
    { label: "Silly Bandz", icon: "toy" },
    { label: "Minecraft block", icon: "lego" },
    { label: "Beats headphones", icon: "headphones" },
  ],
};
