import type { CultureYearInput } from "@/lib/content/schema";

/** 2011 — CULTURAL CONTEXT (general history, not personal). */
export const culture2011: CultureYearInput = {
  year: 2011,
  headline: "Minecraft hits 1.0 and Siri says hello.",
  blurb:
    "Snapchat and Twitch launched, Spotify reached the US, and Skyrim and Minecraft 1.0 arrived within a week of each other in November. The iPhone 4S introduced Siri days after Steve Jobs died, and the final Harry Potter film closed a decade.",
  design:
    "The last, richest year of skeuomorphism: iOS 5's Newsstand shelves and Game Center felt. Windows Phone's Metro tiles hinted at the flat future.",
  internet: [
    { label: "Snapchat launches", kind: "app", icon: "ghost", note: "Disappearing photos, September." },
    { label: "Twitch launches", kind: "site", icon: "stream", note: "Spun out of Justin.tv in June." },
    { label: "Spotify arrives in the US", kind: "app", icon: "music", note: "July, invite-only at first." },
    { label: "Google+", kind: "site", icon: "globe", note: "Circles and Hangouts." },
    { label: "Nyan Cat", kind: "meme", icon: "video", note: "April; a Pop-Tart cat and an endless loop." },
    { label: "Rebecca Black — Friday", kind: "meme", icon: "video", note: "March; the most disliked video of its time." },
    { label: "Rage comics and Trollface", kind: "meme", icon: "smile", note: "\"Y U NO\" and \"Me Gusta\"." },
    { label: "Minecraft YouTubers", kind: "youtube", icon: "video", note: "Yogscast, CaptainSparklez, and Let's Plays as a genre." },
    { label: "Temple Run", kind: "game", icon: "iphone", note: "August; the endless runner everyone had." },
  ],
  tech: [
    { label: "iPhone 4S and Siri", kind: "phone", icon: "iphone", note: "October 4." },
    { label: "iPad 2", kind: "device", icon: "tablet", note: "Thinner, with the Smart Cover." },
    { label: "Nintendo 3DS", kind: "console", icon: "ds", note: "Glasses-free 3D, March." },
    { label: "Kindle Fire", kind: "device", icon: "tablet", note: "A $199 tablet, November." },
    { label: "Chromebook", kind: "computer", icon: "laptop" },
    { label: "Steve Jobs dies", kind: "event", icon: "iphone", note: "October 5." },
    { label: "Samsung Galaxy S II", kind: "phone", icon: "phone" },
    { label: "iMessage", kind: "app", icon: "chat", note: "Blue bubbles arrived with iOS 5." },
  ],
  games: [
    { label: "Minecraft 1.0", kind: "game", icon: "lego", note: "Officially released November 18 at MineCon." },
    { label: "The Elder Scrolls V: Skyrim", kind: "game", icon: "controller", note: "11/11/11." },
    { label: "Portal 2", kind: "game", icon: "desktop" },
    { label: "Batman: Arkham City", kind: "game", icon: "xbox" },
    { label: "Call of Duty: Modern Warfare 3 and Battlefield 3", kind: "game", icon: "controller" },
    { label: "Pokémon Black and White (US)", kind: "game", icon: "ds" },
    { label: "Mario Kart 7 and Super Mario 3D Land", kind: "game", icon: "ds" },
    { label: "The Legend of Zelda: Skyward Sword", kind: "game", icon: "wii" },
    { label: "Terraria, Jetpack Joyride, Tiny Wings", kind: "game", icon: "iphone" },
  ],
  onScreen: [
    { label: "Harry Potter and the Deathly Hallows: Part 2", kind: "movie", icon: "film", note: "July 15; the end of the series." },
    { label: "Game of Thrones premieres", kind: "show", icon: "tv" },
    { label: "Cars 2, Kung Fu Panda 2, Rio", kind: "movie", icon: "film" },
    { label: "Captain America and Thor", kind: "movie", icon: "film" },
    { label: "Rango and Puss in Boots", kind: "movie", icon: "film" },
    { label: "Jessie premieres", kind: "show", icon: "tv" },
    { label: "Annoying Orange", kind: "youtube", icon: "video" },
    { label: "Ultimate Dog Tease", kind: "youtube", icon: "video", note: "\"The maple kind. Yeah.\"" },
  ],
  music: [
    { id: "c2011-rolling", title: "Rolling in the Deep", artist: "Adele" },
    { id: "c2011-partyrock", title: "Party Rock Anthem", artist: "LMFAO" },
    { id: "c2011-giveme", title: "Give Me Everything", artist: "Pitbull ft. Ne-Yo" },
    { id: "c2011-jagger", title: "Moves Like Jagger", artist: "Maroon 5 ft. Christina Aguilera" },
    { id: "c2011-pumpedup", title: "Pumped Up Kicks", artist: "Foster the People" },
    { id: "c2011-superbass", title: "Super Bass", artist: "Nicki Minaj" },
    { id: "c2011-wefoundlove", title: "We Found Love", artist: "Rihanna ft. Calvin Harris" },
  ],
  culture: [
    { label: "Planking", kind: "trend", icon: "smile" },
    { label: "The Royal Wedding", kind: "event", icon: "star", note: "April 29; two billion watched." },
    { label: "Beats and snapbacks", kind: "fashion", icon: "headphones" },
    { label: "Angry Birds plush toys", kind: "toy", icon: "toy" },
    { label: "Netflix's Qwikster mistake", kind: "event", icon: "stream" },
    { label: "Occupy Wall Street", kind: "event", icon: "flag", note: "September; \"We are the 99%.\"" },
    { label: "Charlie Sheen \"Winning\"", kind: "slang", icon: "smile" },
  ],
  capsule: [
    { label: "Minecraft creeper", icon: "lego" },
    { label: "3DS", icon: "ds" },
    { label: "Siri", icon: "mic" },
    { label: "Nyan Cat", icon: "star" },
    { label: "Skyrim helmet", icon: "controller" },
    { label: "Spotify", icon: "music" },
  ],
};
