import type { CultureYearInput } from "@/lib/content/schema";

/** 2012 — CULTURAL CONTEXT (general history, not personal). */
export const culture2012: CultureYearInput = {
  year: 2012,
  headline: "Gangnam Style hits a billion.",
  blurb:
    "Facebook bought Instagram and went public, Windows 8 turned the desktop into tiles, and the iPhone 5 stretched to four inches. The Avengers assembled, Minecraft came to Xbox, and the world did not end on December 21.",
    design:
    "The tipping point: iOS 6 was the last skeuomorphic release, Windows 8 went fully flat with coloured tiles, and Instagram's Kelvin and Earlybird filters aged every photo on purpose.",
  internet: [
    { label: "Gangnam Style", kind: "youtube", icon: "video", note: "July; the first video to a billion views, in December." },
    { label: "Facebook buys Instagram", kind: "site", icon: "camera", note: "$1 billion in April; Instagram for Android arrived the same week." },
    { label: "Facebook IPO", kind: "event", icon: "globe", note: "May 18." },
    { label: "Tumblr and Pinterest at their peak", kind: "site", icon: "blog" },
    { label: "Kony 2012", kind: "youtube", icon: "video", note: "March; the fastest-spreading video to that point." },
    { label: "Grumpy Cat, Bad Luck Brian, Overly Attached Girlfriend", kind: "meme", icon: "smile" },
    { label: "Ermahgerd", kind: "meme", icon: "smile" },
    { label: "Draw Something", kind: "game", icon: "iphone", note: "Fifty million downloads in fifty days." },
    { label: "Kickstarter's breakout year", kind: "site", icon: "rocket", note: "Pebble and Ouya." },
  ],
  tech: [
    { label: "iPhone 5", kind: "phone", icon: "iphone", note: "Lightning connector and a taller screen." },
    { label: "Windows 8 and Surface", kind: "computer", icon: "window", note: "October 26; tiles on a desktop." },
    { label: "iPad mini and the Retina iPad", kind: "device", icon: "tablet" },
    { label: "Nexus 7", kind: "device", icon: "tablet" },
    { label: "Wii U", kind: "console", icon: "wii", note: "November 18; a controller with a screen." },
    { label: "Apple Maps", kind: "app", icon: "map", note: "iOS 6's rough first version." },
    { label: "Galaxy S III", kind: "phone", icon: "phone" },
    { label: "Raspberry Pi", kind: "computer", icon: "desktop", note: "A $35 computer, February." },
  ],
  games: [
    { label: "Minecraft: Xbox 360 Edition", kind: "game", icon: "xbox", note: "May; split-screen on the couch." },
    { label: "Temple Run and Subway Surfers", kind: "game", icon: "iphone" },
    { label: "Clash of Clans", kind: "game", icon: "tablet", note: "August." },
    { label: "Pokémon Black 2 and White 2", kind: "game", icon: "ds" },
    { label: "Halo 4 and Black Ops II", kind: "game", icon: "xbox" },
    { label: "Slender: The Eight Pages", kind: "game", icon: "desktop", note: "Free, terrifying, all over YouTube." },
    { label: "Journey and FTL", kind: "game", icon: "playstation" },
    { label: "New Super Mario Bros. 2 and U", kind: "game", icon: "wii" },
    { label: "Borderlands 2 and Mass Effect 3", kind: "game", icon: "controller" },
  ],
  onScreen: [
    { label: "The Avengers", kind: "movie", icon: "film" },
    { label: "The Dark Knight Rises", kind: "movie", icon: "film" },
    { label: "The Hunger Games", kind: "movie", icon: "film" },
    { label: "Skyfall", kind: "movie", icon: "film" },
    { label: "Brave and Wreck-It Ralph", kind: "movie", icon: "film" },
    { label: "Hotel Transylvania and The Lorax", kind: "movie", icon: "film" },
    { label: "Gravity Falls premieres", kind: "show", icon: "tv" },
    { label: "Breaking Bad season 5 begins", kind: "show", icon: "tv" },
    { label: "The Walking Dead's biggest year", kind: "show", icon: "tv" },
  ],
  music: [
    { id: "c2012-callmemaybe", title: "Call Me Maybe", artist: "Carly Rae Jepsen" },
    { id: "c2012-somebody", title: "Somebody That I Used to Know", artist: "Gotye ft. Kimbra" },
    { id: "c2012-gangnam", title: "Gangnam Style", artist: "PSY" },
    { id: "c2012-weareyoung", title: "We Are Young", artist: "fun. ft. Janelle Monáe" },
    { id: "c2012-payphone", title: "Payphone", artist: "Maroon 5 ft. Wiz Khalifa" },
    { id: "c2012-wmyb", title: "What Makes You Beautiful", artist: "One Direction" },
    { id: "c2012-thriftshop", title: "Thrift Shop", artist: "Macklemore & Ryan Lewis" },
  ],
  culture: [
    { label: "London 2012 Olympics", kind: "event", icon: "trophy" },
    { label: "Curiosity lands on Mars", kind: "event", icon: "rocket", note: "August 5." },
    { label: "Felix Baumgartner's space jump", kind: "event", icon: "rocket", note: "Streamed live on YouTube, October 14." },
    { label: "The Mayan calendar \"end of the world\"", kind: "meme", icon: "moon", note: "December 21." },
    { label: "Yolo", kind: "slang", icon: "smile" },
    { label: "Snapbacks and galaxy print", kind: "fashion", icon: "star" },
    { label: "One Direction mania", kind: "trend", icon: "music" },
    { label: "Beanie Boos", kind: "toy", icon: "toy" },
  ],
  capsule: [
    { label: "Instagram filter", icon: "camera" },
    { label: "Windows 8 tile", icon: "window" },
    { label: "Wii U GamePad", icon: "wii" },
    { label: "iPhone 5", icon: "iphone" },
    { label: "Slender page", icon: "book" },
    { label: "Olympic torch", icon: "trophy" },
  ],
};
