import type { CultureYearInput } from "@/lib/content/schema";

/** 2013 — CULTURAL CONTEXT (general history, not personal). */
export const culture2013: CultureYearInput = {
  year: 2013,
  headline: "Everything goes flat.",
  blurb:
    "iOS 7 threw out the leather and linen in September, Vine launched six-second loops in January, and Snapchat added Stories in October. The PS4 and Xbox One arrived a week apart in November, GTA V made a billion dollars in three days, and Frozen closed the year.",
  design:
    "iOS 7: thin Helvetica, white space, translucent blur, bright flat icons. Long shadows and pastel gradients spread across every app and website within months.",
  internet: [
    { label: "Vine launches", kind: "app", icon: "reel", note: "January; six seconds, looped." },
    { label: "Snapchat Stories", kind: "app", icon: "ghost", note: "October; 24 hours and gone." },
    { label: "Yahoo buys Tumblr", kind: "site", icon: "blog", note: "$1.1 billion in May." },
    { label: "Instagram adds video", kind: "app", icon: "camera" },
    { label: "Harlem Shake", kind: "meme", icon: "video", note: "February; thirty seconds, a helmet, chaos." },
    { label: "What Does the Fox Say?", kind: "youtube", icon: "video" },
    { label: "Doge", kind: "meme", icon: "smile", note: "Such meme. Very 2013." },
    { label: "PewDiePie becomes the most-subscribed channel", kind: "youtube", icon: "video", note: "August." },
    { label: "\"Selfie\" is Oxford's word of the year", kind: "slang", icon: "camera" },
    { label: "Twitter IPO", kind: "event", icon: "bird", note: "November." },
  ],
  tech: [
    { label: "iOS 7", kind: "app", icon: "iphone", note: "September 18; the flat redesign." },
    { label: "iPhone 5s and 5c", kind: "phone", icon: "iphone", note: "Touch ID and five colours." },
    { label: "PlayStation 4", kind: "console", icon: "playstation", note: "November 15." },
    { label: "Xbox One", kind: "console", icon: "xbox", note: "November 22; Kinect in the box." },
    { label: "Chromecast", kind: "device", icon: "tv", note: "$35, July." },
    { label: "Google Glass Explorer edition", kind: "device", icon: "headset" },
    { label: "Nexus 5 and Galaxy S4", kind: "phone", icon: "phone" },
    { label: "Netflix originals begin", kind: "app", icon: "stream", note: "House of Cards in February, Orange Is the New Black in July." },
  ],
  games: [
    { label: "Grand Theft Auto V", kind: "game", icon: "controller", note: "September 17." },
    { label: "The Last of Us", kind: "game", icon: "playstation" },
    { label: "Pokémon X and Y", kind: "game", icon: "ds", note: "The first worldwide simultaneous launch, October 12." },
    { label: "Animal Crossing: New Leaf (US)", kind: "game", icon: "ds" },
    { label: "Candy Crush Saga", kind: "game", icon: "iphone", note: "The most downloaded app of the year." },
    { label: "Minecraft on PS3 and everywhere", kind: "game", icon: "lego" },
    { label: "BioShock Infinite", kind: "game", icon: "xbox" },
    { label: "Super Mario 3D World and A Link Between Worlds", kind: "game", icon: "wii" },
    { label: "Flappy Bird released", kind: "game", icon: "iphone", note: "May; it went viral in January 2014." },
  ],
  onScreen: [
    { label: "Frozen", kind: "movie", icon: "snow", note: "November; \"Let It Go\" everywhere for a year." },
    { label: "Despicable Me 2 and Monsters University", kind: "movie", icon: "film" },
    { label: "Iron Man 3 and Man of Steel", kind: "movie", icon: "film" },
    { label: "The Hunger Games: Catching Fire", kind: "movie", icon: "film" },
    { label: "Gravity", kind: "movie", icon: "rocket" },
    { label: "Breaking Bad finale", kind: "show", icon: "tv", note: "September 29." },
    { label: "House of Cards and Orange Is the New Black", kind: "show", icon: "stream" },
    { label: "Steven Universe premieres", kind: "show", icon: "tv", note: "November." },
    { label: "Sharknado", kind: "movie", icon: "tv", note: "A Syfy movie that Twitter turned into an event." },
  ],
  music: [
    { id: "c2013-thriftshop", title: "Thrift Shop", artist: "Macklemore & Ryan Lewis ft. Wanz" },
    { id: "c2013-blurredlines", title: "Blurred Lines", artist: "Robin Thicke ft. T.I. & Pharrell" },
    { id: "c2013-radioactive", title: "Radioactive", artist: "Imagine Dragons" },
    { id: "c2013-royals", title: "Royals", artist: "Lorde" },
    { id: "c2013-getlucky", title: "Get Lucky", artist: "Daft Punk ft. Pharrell Williams" },
    { id: "c2013-roar", title: "Roar", artist: "Katy Perry" },
    { id: "c2013-wakemeup", title: "Wake Me Up", artist: "Avicii" },
    { id: "c2013-cantholdus", title: "Can't Hold Us", artist: "Macklemore & Ryan Lewis" },
  ],
  culture: [
    { label: "The Harlem Shake", kind: "trend", icon: "video" },
    { label: "Selfies", kind: "trend", icon: "camera" },
    { label: "Twerking at the VMAs", kind: "event", icon: "mic" },
    { label: "Rainbow Loom", kind: "toy", icon: "toy", note: "Rubber-band bracelets on every wrist." },
    { label: "Galaxy print and Vans", kind: "fashion", icon: "star" },
    { label: "Netflix binge-watching", kind: "trend", icon: "stream", note: "Whole seasons released at once." },
    { label: "Cronut", kind: "food", icon: "pizza" },
    { label: "Twitter fights and hashtags", kind: "trend", icon: "bird" },
  ],
  capsule: [
    { label: "iOS 7 icon", icon: "iphone" },
    { label: "Vine loop", icon: "reel" },
    { label: "PS4 controller", icon: "playstation" },
    { label: "Rainbow Loom", icon: "toy" },
    { label: "Doge", icon: "smile" },
    { label: "Frozen snowflake", icon: "snow" },
  ],
};
