import type { CultureYearInput } from "@/lib/content/schema";

/** 2014 — CULTURAL CONTEXT (general history, not personal). */
export const culture2014: CultureYearInput = {
  year: 2014,
  headline: "Buckets of ice and a bird that flaps.",
  blurb:
    "Flappy Bird was pulled in February, the Ice Bucket Challenge took over August, and Vine minted its first stars. Apple went big with the iPhone 6, Google launched Material Design, Amazon bought Twitch, Microsoft bought Minecraft, and Five Nights at Freddy's scared a generation of YouTubers.",
  design:
    "Material Design: paper layers, bold colour, ripple effects, floating action buttons. Flat design matured, and the iPhone 6's rounded aluminium replaced hard edges.",
  internet: [
    { label: "Ice Bucket Challenge", kind: "meme", icon: "cloud", note: "August; $115 million raised for ALS research." },
    { label: "Flappy Bird removed", kind: "game", icon: "iphone", note: "February 10; phones with it installed sold on eBay." },
    { label: "Vine stars", kind: "app", icon: "reel", note: "Nash Grier, Cameron Dallas, Lele Pons, King Bach." },
    { label: "Amazon buys Twitch", kind: "site", icon: "stream", note: "$970 million, August." },
    { label: "Microsoft buys Minecraft", kind: "game", icon: "lego", note: "$2.5 billion, September." },
    { label: "Facebook buys WhatsApp and Oculus", kind: "site", icon: "globe" },
    { label: "Alex from Target", kind: "meme", icon: "smile", note: "November." },
    { label: "\"But that's none of my business\"", kind: "meme", icon: "smile", note: "Kermit and his tea." },
    { label: "\"On fleek\" and \"Yeet\"", kind: "slang", icon: "reel", note: "Both born on Vine." },
    { label: "MLG montage parodies", kind: "youtube", icon: "video", note: "Airhorns, Doritos, Mountain Dew." },
  ],
  tech: [
    { label: "iPhone 6 and 6 Plus", kind: "phone", icon: "iphone", note: "September; bigger screens and Apple Pay." },
    { label: "Apple Watch announced", kind: "device", icon: "watch" },
    { label: "Material Design and Android Lollipop", kind: "app", icon: "phone", note: "June and November." },
    { label: "Amazon Echo (invite only)", kind: "device", icon: "speaker", note: "\"Alexa\" enters the house in November." },
    { label: "Hearthstone", kind: "game", icon: "tablet", note: "March." },
    { label: "PlayStation 4 pulls ahead", kind: "console", icon: "playstation" },
    { label: "GoPro everywhere", kind: "device", icon: "camcorder" },
    { label: "Selfie sticks", kind: "device", icon: "camera" },
  ],
  games: [
    { label: "Five Nights at Freddy's", kind: "game", icon: "desktop", note: "August; jump scares as YouTube content." },
    { label: "Mario Kart 8", kind: "game", icon: "wii", note: "May; the Luigi death stare." },
    { label: "Super Smash Bros. for 3DS and Wii U", kind: "game", icon: "wii" },
    { label: "Pokémon Omega Ruby and Alpha Sapphire", kind: "game", icon: "ds" },
    { label: "Destiny", kind: "game", icon: "playstation" },
    { label: "2048 and Crossy Road", kind: "game", icon: "iphone" },
    { label: "Titanfall and Shovel Knight", kind: "game", icon: "xbox" },
    { label: "Goat Simulator", kind: "game", icon: "desktop" },
    { label: "Minecraft's biggest year on YouTube", kind: "game", icon: "lego", note: "Stampy, DanTDM, and the Hunger Games servers." },
  ],
  onScreen: [
    { label: "Guardians of the Galaxy", kind: "movie", icon: "rocket" },
    { label: "The Lego Movie", kind: "movie", icon: "lego", note: "\"Everything Is Awesome.\"" },
    { label: "Big Hero 6 and How to Train Your Dragon 2", kind: "movie", icon: "film" },
    { label: "Interstellar", kind: "movie", icon: "rocket" },
    { label: "Captain America: The Winter Soldier", kind: "movie", icon: "film" },
    { label: "The Fault in Our Stars", kind: "movie", icon: "book" },
    { label: "Mockingjay: Part 1", kind: "movie", icon: "film" },
    { label: "The Flash and Gotham premiere", kind: "show", icon: "tv" },
    { label: "Too Many Cooks", kind: "youtube", icon: "video", note: "An Adult Swim short that broke the internet in November." },
  ],
  music: [
    { id: "c2014-happy", title: "Happy", artist: "Pharrell Williams" },
    { id: "c2014-allaboutthatbass", title: "All About That Bass", artist: "Meghan Trainor" },
    { id: "c2014-shakeitoff", title: "Shake It Off", artist: "Taylor Swift" },
    { id: "c2014-fancy", title: "Fancy", artist: "Iggy Azalea ft. Charli XCX" },
    { id: "c2014-darkhorse", title: "Dark Horse", artist: "Katy Perry ft. Juicy J" },
    { id: "c2014-turndown", title: "Turn Down for What", artist: "DJ Snake & Lil Jon" },
    { id: "c2014-uptownfunk", title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", note: "Released November; owned 2015." },
    { id: "c2014-letitgo", title: "Let It Go", artist: "Idina Menzel" },
  ],
  culture: [
    { label: "Ice Bucket Challenge", kind: "trend", icon: "cloud" },
    { label: "Vine dances", kind: "trend", icon: "reel" },
    { label: "Loom bands", kind: "toy", icon: "toy" },
    { label: "Snapback and Jordans", kind: "fashion", icon: "star" },
    { label: "Frozen merchandise everywhere", kind: "product", icon: "snow" },
    { label: "Sochi Olympics and the Brazil World Cup", kind: "event", icon: "trophy" },
    { label: "Ebola in the headlines", kind: "event", icon: "flag" },
    { label: "\"Bae\" and \"Basic\"", kind: "slang", icon: "smile" },
  ],
  capsule: [
    { label: "Ice bucket", icon: "cloud" },
    { label: "Flappy Bird", icon: "bird" },
    { label: "iPhone 6", icon: "iphone" },
    { label: "Freddy Fazbear", icon: "ghost" },
    { label: "Lego brick", icon: "lego" },
    { label: "Selfie stick", icon: "camera" },
  ],
};
