import type { CultureYearInput } from "@/lib/content/schema";

/** 2015 — CULTURAL CONTEXT (general history, not personal). */
export const culture2015: CultureYearInput = {
  year: 2015,
  headline: "The dress, the watch, and the whip.",
  blurb:
    "Apple Watch and Apple Music launched, Windows 10 arrived, and Discord opened in May. Star Wars came back in December, Undertale and Rocket League became word-of-mouth hits, and everyone argued about whether the dress was blue or gold.",
  design:
    "Flat design with depth: Material Design adoption, Windows 10's return to the desktop, and Snapchat yellow. Hoverboards and rose gold made hardware fashion again.",
  internet: [
    { label: "The Dress", kind: "meme", icon: "smile", note: "February 26; blue and black, or white and gold." },
    { label: "Discord launches", kind: "app", icon: "chat", note: "May; voice chat for gamers, then for everyone." },
    { label: "Periscope and Meerkat", kind: "app", icon: "video", note: "Live streaming from a phone." },
    { label: "Snapchat lenses and Discover", kind: "app", icon: "ghost", note: "The rainbow-vomit filter, September." },
    { label: "Instagram drops the square", kind: "app", icon: "camera" },
    { label: "Google Photos", kind: "app", icon: "camera", note: "Free unlimited backups, May." },
    { label: "Left Shark", kind: "meme", icon: "smile", note: "Super Bowl halftime, February." },
    { label: "Pizza Rat", kind: "meme", icon: "pizza", note: "September." },
    { label: "\"Why you always lying\"", kind: "meme", icon: "video" },
    { label: "Deez Nuts", kind: "meme", icon: "smile", note: "March." },
    { label: "YouTube Red and YouTube Gaming", kind: "site", icon: "video" },
  ],
  tech: [
    { label: "Apple Watch", kind: "device", icon: "watch", note: "April 24." },
    { label: "Apple Music", kind: "app", icon: "music", note: "June 30, with Beats 1 radio." },
    { label: "Windows 10", kind: "computer", icon: "window", note: "July 29; the Start menu returned." },
    { label: "iPhone 6s and 3D Touch", kind: "phone", icon: "iphone" },
    { label: "iPad Pro and Apple Pencil", kind: "device", icon: "tablet" },
    { label: "Amazon Echo goes public", kind: "device", icon: "speaker", note: "June." },
    { label: "Hoverboards", kind: "device", icon: "skateboard", note: "The holiday's must-have, and fire hazard." },
    { label: "Tesla Model X and Autopilot", kind: "device", icon: "car" },
    { label: "Fitbit's peak", kind: "device", icon: "watch" },
  ],
  games: [
    { label: "Undertale", kind: "game", icon: "desktop", note: "September; a one-person RPG that took over Tumblr." },
    { label: "Rocket League", kind: "game", icon: "car", note: "July; free on PlayStation Plus." },
    { label: "Splatoon", kind: "game", icon: "wii", note: "May." },
    { label: "Super Mario Maker", kind: "game", icon: "wii", note: "September." },
    { label: "Fallout 4", kind: "game", icon: "controller", note: "November 10." },
    { label: "The Witcher 3: Wild Hunt", kind: "game", icon: "controller" },
    { label: "Agar.io", kind: "game", icon: "globe", note: "April; browser games return." },
    { label: "Geometry Dash's boom", kind: "game", icon: "iphone" },
    { label: "Star Wars Battlefront and Black Ops III", kind: "game", icon: "playstation" },
    { label: "Bloodborne and Metal Gear Solid V", kind: "game", icon: "playstation" },
  ],
  onScreen: [
    { label: "Star Wars: The Force Awakens", kind: "movie", icon: "rocket", note: "December 18." },
    { label: "Jurassic World", kind: "movie", icon: "film" },
    { label: "Inside Out", kind: "movie", icon: "film" },
    { label: "Avengers: Age of Ultron and Ant-Man", kind: "movie", icon: "film" },
    { label: "Minions", kind: "movie", icon: "film" },
    { label: "Mad Max: Fury Road and The Martian", kind: "movie", icon: "film" },
    { label: "Mr. Robot and Better Call Saul premiere", kind: "show", icon: "tv" },
    { label: "Star vs. the Forces of Evil premieres", kind: "show", icon: "tv" },
    { label: "Jessica Jones and Daredevil", kind: "show", icon: "stream" },
    { label: "Markiplier, Jacksepticeye, PewDiePie", kind: "youtube", icon: "video", note: "Let's Play at its peak." },
  ],
  music: [
    { id: "c2015-uptownfunk", title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars" },
    { id: "c2015-seeyouagain", title: "See You Again", artist: "Wiz Khalifa ft. Charlie Puth" },
    { id: "c2015-trapqueen", title: "Trap Queen", artist: "Fetty Wap" },
    { id: "c2015-whip", title: "Watch Me (Whip/Nae Nae)", artist: "Silentó" },
    { id: "c2015-hotlinebling", title: "Hotline Bling", artist: "Drake" },
    { id: "c2015-hello", title: "Hello", artist: "Adele" },
    { id: "c2015-cantfeelmyface", title: "Can't Feel My Face", artist: "The Weeknd" },
    { id: "c2015-leanon", title: "Lean On", artist: "Major Lazer & DJ Snake ft. MØ" },
    { id: "c2015-stressedout", title: "Stressed Out", artist: "Twenty One Pilots" },
  ],
  culture: [
    { label: "The Whip and Nae Nae", kind: "trend", icon: "music" },
    { label: "Hamilton opens on Broadway", kind: "event", icon: "mic", note: "August." },
    { label: "New Horizons reaches Pluto", kind: "event", icon: "rocket", note: "July 14." },
    { label: "\"Netflix and chill\"", kind: "slang", icon: "stream" },
    { label: "\"Squad goals\" and \"lit\"", kind: "slang", icon: "smile" },
    { label: "Hoverboards and Heelys nostalgia", kind: "trend", icon: "skateboard" },
    { label: "Shopkins", kind: "toy", icon: "toy" },
    { label: "Adidas Superstars and Yeezys", kind: "fashion", icon: "star" },
  ],
  capsule: [
    { label: "Apple Watch", icon: "watch" },
    { label: "The dress", icon: "smile" },
    { label: "Hoverboard", icon: "skateboard" },
    { label: "Discord", icon: "chat" },
    { label: "Lightsaber", icon: "rocket" },
    { label: "Undertale heart", icon: "heart" },
  ],
};
