import type { CultureYearInput } from "@/lib/content/schema";

/** 2016 — CULTURAL CONTEXT (general history, not personal). */
export const culture2016: CultureYearInput = {
  year: 2016,
  headline: "Pokémon in the park, no headphone jack in the phone.",
  blurb:
    "Pokémon Go emptied living rooms in July, Instagram cloned Stories in August, and Vine announced its shutdown in October. Apple removed the headphone jack and introduced AirPods, VR headsets shipped, Overwatch launched, and Stranger Things arrived on Netflix.",
  design:
    "Instagram's gradient icon in May signalled a return to colour. Bold gradients, rounded cards, and the vertical Stories format began reshaping every app.",
  internet: [
    { label: "Pokémon Go", kind: "game", icon: "phone", note: "July 6; the biggest mobile launch ever." },
    { label: "Instagram Stories", kind: "app", icon: "camera", note: "August 2." },
    { label: "Vine shutdown announced", kind: "app", icon: "reel", note: "October; the app closed in January 2017." },
    { label: "Musical.ly boom", kind: "app", icon: "music", note: "Lip-sync videos, later merged into TikTok." },
    { label: "Harambe", kind: "meme", icon: "smile", note: "May through the end of the year." },
    { label: "Damn Daniel", kind: "meme", icon: "video", note: "February; \"back at it again with the white Vans\"." },
    { label: "Mannequin Challenge", kind: "meme", icon: "video", note: "November." },
    { label: "Bottle flipping", kind: "meme", icon: "video", note: "May; a talent show video started it." },
    { label: "Pen Pineapple Apple Pen", kind: "meme", icon: "video" },
    { label: "Facebook Live and Snapchat Spectacles", kind: "app", icon: "video" },
    { label: "Evil Kermit and Arthur's fist", kind: "meme", icon: "smile" },
  ],
  tech: [
    { label: "iPhone 7", kind: "phone", icon: "iphone", note: "September; no headphone jack, water resistant." },
    { label: "AirPods", kind: "device", icon: "earbuds", note: "December." },
    { label: "Google Pixel and Google Assistant", kind: "phone", icon: "phone" },
    { label: "Google Home", kind: "device", icon: "speaker" },
    { label: "PlayStation VR, Oculus Rift, HTC Vive", kind: "device", icon: "headset" },
    { label: "PS4 Pro and Xbox One S", kind: "console", icon: "playstation" },
    { label: "Nintendo Switch revealed", kind: "console", icon: "switch", note: "October 20 trailer." },
    { label: "NES Classic", kind: "console", icon: "controller", note: "November; sold out instantly." },
    { label: "Galaxy Note 7 recall", kind: "phone", icon: "battery" },
  ],
  games: [
    { label: "Overwatch", kind: "game", icon: "desktop", note: "May 24." },
    { label: "Pokémon Sun and Moon", kind: "game", icon: "ds", note: "November 18." },
    { label: "Stardew Valley", kind: "game", icon: "leaf", note: "February." },
    { label: "Clash Royale", kind: "game", icon: "iphone", note: "March." },
    { label: "Slither.io", kind: "game", icon: "globe" },
    { label: "Uncharted 4 and Doom", kind: "game", icon: "playstation" },
    { label: "Battlefield 1 and Titanfall 2", kind: "game", icon: "xbox" },
    { label: "Dark Souls III and Final Fantasy XV", kind: "game", icon: "controller" },
    { label: "Minecraft: Pocket Edition on everything", kind: "game", icon: "lego" },
  ],
  onScreen: [
    { label: "Stranger Things premieres", kind: "show", icon: "stream", note: "July 15." },
    { label: "Zootopia and Finding Dory", kind: "movie", icon: "film" },
    { label: "Moana", kind: "movie", icon: "film" },
    { label: "Captain America: Civil War", kind: "movie", icon: "film" },
    { label: "Rogue One", kind: "movie", icon: "rocket" },
    { label: "Deadpool", kind: "movie", icon: "film" },
    { label: "The Jungle Book and Doctor Strange", kind: "movie", icon: "film" },
    { label: "Westworld, The Crown, Atlanta premiere", kind: "show", icon: "tv" },
    { label: "Planet Earth II", kind: "show", icon: "tv" },
    { label: "The Loud House premieres", kind: "show", icon: "tv" },
  ],
  music: [
    { id: "c2016-closer", title: "Closer", artist: "The Chainsmokers ft. Halsey" },
    { id: "c2016-onedance", title: "One Dance", artist: "Drake ft. Wizkid & Kyla" },
    { id: "c2016-loveyourself", title: "Love Yourself", artist: "Justin Bieber" },
    { id: "c2016-cantstop", title: "Can't Stop the Feeling!", artist: "Justin Timberlake" },
    { id: "c2016-work", title: "Work", artist: "Rihanna ft. Drake" },
    { id: "c2016-panda", title: "Panda", artist: "Desiigner" },
    { id: "c2016-heathens", title: "Heathens", artist: "Twenty One Pilots" },
    { id: "c2016-blackbeatles", title: "Black Beatles", artist: "Rae Sremmurd ft. Gucci Mane", note: "The Mannequin Challenge song." },
    { id: "c2016-cheapthrills", title: "Cheap Thrills", artist: "Sia" },
  ],
  culture: [
    { label: "Pokémon Go summer", kind: "trend", icon: "phone" },
    { label: "Rio Olympics", kind: "event", icon: "trophy" },
    { label: "The Cubs win the World Series", kind: "event", icon: "ball", note: "First since 1908." },
    { label: "A US election year", kind: "event", icon: "flag", note: "November 8." },
    { label: "Hamilton mania", kind: "trend", icon: "mic" },
    { label: "Juju on That Beat", kind: "trend", icon: "music" },
    { label: "Fidget cubes and slime", kind: "toy", icon: "toy" },
    { label: "Yeezys, Supreme, and bomber jackets", kind: "fashion", icon: "star" },
    { label: "\"Dab\"", kind: "trend", icon: "smile" },
  ],
  capsule: [
    { label: "Poké Ball", icon: "ball" },
    { label: "AirPods", icon: "earbuds" },
    { label: "VR headset", icon: "headset" },
    { label: "Water bottle", icon: "cloud" },
    { label: "Eggo waffle", icon: "stream" },
    { label: "Overwatch", icon: "desktop" },
  ],
};
