import type { CultureYearInput } from "@/lib/content/schema";

/** 2017 — CULTURAL CONTEXT (general history, not personal). */
export const culture2017: CultureYearInput = {
  year: 2017,
  headline: "Where we droppin'?",
  blurb:
    "Fortnite Battle Royale launched in September and Nintendo Switch in March, with Breath of the Wild and Super Mario Odyssey on either side of it. The iPhone X removed the home button, Despacito became the most-watched video ever, fidget spinners peaked in spring, and musical.ly was sold to ByteDance in November.",
  design:
    "The notch. Edge-to-edge screens, gesture navigation, and the beginnings of dark mode. Bold type, duotone gradients, and Spotify green as the colour of the year.",
  internet: [
    { label: "Fortnite Battle Royale", kind: "game", icon: "controller", note: "September 26; free to play." },
    { label: "Despacito", kind: "youtube", icon: "video", note: "The most-viewed video on YouTube by August." },
    { label: "Fidget spinners", kind: "trend", icon: "toy", note: "Everywhere in April and May." },
    { label: "Distracted Boyfriend", kind: "meme", icon: "smile", note: "August." },
    { label: "\"Cash me outside\" and Salt Bae", kind: "meme", icon: "smile", note: "January." },
    { label: "Expanding Brain", kind: "meme", icon: "smile" },
    { label: "Twitter doubles to 280 characters", kind: "site", icon: "bird", note: "November." },
    { label: "Musical.ly sold to ByteDance", kind: "app", icon: "music", note: "November; the road to TikTok." },
    { label: "Jake Paul and Team 10", kind: "youtube", icon: "video", note: "\"It's Everyday Bro.\"" },
    { label: "Ugandan Knuckles", kind: "meme", icon: "smile", note: "December, in VRChat." },
    { label: "Bitcoin nears $20,000", kind: "event", icon: "key", note: "December." },
  ],
  tech: [
    { label: "Nintendo Switch", kind: "console", icon: "switch", note: "March 3." },
    { label: "iPhone X", kind: "phone", icon: "iphone", note: "November 3; Face ID and the notch." },
    { label: "iPhone 8 and AirPods everywhere", kind: "phone", icon: "earbuds" },
    { label: "Xbox One X", kind: "console", icon: "xbox" },
    { label: "SNES Classic", kind: "console", icon: "controller" },
    { label: "Amazon Echo Show and Google Home Mini", kind: "device", icon: "speaker" },
    { label: "Samsung Galaxy S8", kind: "phone", icon: "phone", note: "The first mainstream all-screen Android." },
    { label: "Solar eclipse across the US", kind: "event", icon: "sun", note: "August 21." },
  ],
  games: [
    { label: "The Legend of Zelda: Breath of the Wild", kind: "game", icon: "switch", note: "March 3." },
    { label: "Super Mario Odyssey", kind: "game", icon: "switch", note: "October 27." },
    { label: "Fortnite Battle Royale", kind: "game", icon: "controller" },
    { label: "PlayerUnknown's Battlegrounds", kind: "game", icon: "desktop", note: "March; winner winner chicken dinner." },
    { label: "Cuphead", kind: "game", icon: "xbox" },
    { label: "Splatoon 2 and Mario Kart 8 Deluxe", kind: "game", icon: "switch" },
    { label: "Hollow Knight", kind: "game", icon: "desktop" },
    { label: "Persona 5 and Horizon Zero Dawn", kind: "game", icon: "playstation" },
    { label: "Getting Over It", kind: "game", icon: "desktop", note: "December; streamer rage as a genre." },
    { label: "Star Wars Battlefront II loot boxes", kind: "game", icon: "xbox", note: "The most downvoted comment in Reddit history." },
  ],
  onScreen: [
    { label: "Stranger Things 2", kind: "show", icon: "stream" },
    { label: "Wonder Woman and Thor: Ragnarok", kind: "movie", icon: "film" },
    { label: "Spider-Man: Homecoming", kind: "movie", icon: "film" },
    { label: "Coco", kind: "movie", icon: "music" },
    { label: "It", kind: "movie", icon: "film", note: "September." },
    { label: "Star Wars: The Last Jedi", kind: "movie", icon: "rocket" },
    { label: "Get Out and Baby Driver", kind: "movie", icon: "film" },
    { label: "Rick and Morty season 3", kind: "show", icon: "tv", note: "The Szechuan sauce episode." },
    { label: "Riverdale and 13 Reasons Why premiere", kind: "show", icon: "tv" },
    { label: "DuckTales reboot", kind: "show", icon: "tv" },
  ],
  music: [
    { id: "c2017-shapeofyou", title: "Shape of You", artist: "Ed Sheeran" },
    { id: "c2017-despacito", title: "Despacito", artist: "Luis Fonsi & Daddy Yankee ft. Justin Bieber" },
    { id: "c2017-humble", title: "HUMBLE.", artist: "Kendrick Lamar" },
    { id: "c2017-bodakyellow", title: "Bodak Yellow", artist: "Cardi B" },
    { id: "c2017-rockstar", title: "Rockstar", artist: "Post Malone ft. 21 Savage" },
    { id: "c2017-xotourllif3", title: "XO Tour Llif3", artist: "Lil Uzi Vert" },
    { id: "c2017-thunder", title: "Thunder", artist: "Imagine Dragons" },
    { id: "c2017-havana", title: "Havana", artist: "Camila Cabello ft. Young Thug" },
    { id: "c2017-lwymmd", title: "Look What You Made Me Do", artist: "Taylor Swift" },
  ],
  culture: [
    { label: "Fidget spinners", kind: "toy", icon: "toy" },
    { label: "SoundCloud rap", kind: "trend", icon: "music", note: "Lil Pump, XXXTentacion, Lil Peep." },
    { label: "Supreme and streetwear drops", kind: "fashion", icon: "star" },
    { label: "Slime videos", kind: "trend", icon: "video" },
    { label: "Unicorn Frappuccino", kind: "food", icon: "sparkle" },
    { label: "The Great American Eclipse", kind: "event", icon: "sun" },
    { label: "\"Lit\", \"woke\", \"savage\"", kind: "slang", icon: "smile" },
    { label: "Wonder Woman and #MeToo", kind: "event", icon: "flag", note: "A year of reckoning in October." },
  ],
  capsule: [
    { label: "Switch Joy-Con", icon: "switch" },
    { label: "Fidget spinner", icon: "toy" },
    { label: "Battle Bus", icon: "rocket" },
    { label: "iPhone X", icon: "iphone" },
    { label: "Eclipse glasses", icon: "sun" },
    { label: "Sheikah Slate", icon: "tablet" },
  ],
};
