import type { CultureYearInput } from "@/lib/content/schema";

/** 2018 — CULTURAL CONTEXT (general history, not personal). */
export const culture2018: CultureYearInput = {
  year: 2018,
  headline: "The year of Fortnite.",
  blurb:
    "Ninja and Drake streamed together in March, Fortnite came to phones and Switch, and the rocket launch in June was the first live in-game event. TikTok absorbed musical.ly in August, Black Panther and Infinity War dominated theatres, and God of War and Red Dead Redemption 2 defined console gaming.",
  design:
    "Dark mode arrives (macOS Mojave). Gradients, glass, and neon accents; gaming's RGB aesthetic goes mainstream. Every app copies Stories.",
  internet: [
    { label: "Ninja and Drake play Fortnite", kind: "event", icon: "stream", note: "March 14; 600,000 concurrent viewers on Twitch." },
    { label: "TikTok merges with musical.ly", kind: "app", icon: "music", note: "August 2." },
    { label: "Yanny or Laurel", kind: "meme", icon: "volume", note: "May." },
    { label: "Tide Pod challenge", kind: "meme", icon: "bug", note: "January; do not." },
    { label: "Ugandan Knuckles", kind: "meme", icon: "smile" },
    { label: "Surprised Pikachu", kind: "meme", icon: "smile", note: "September." },
    { label: "Big Chungus", kind: "meme", icon: "smile", note: "December." },
    { label: "Bongo Cat", kind: "meme", icon: "music" },
    { label: "Kiki Challenge", kind: "meme", icon: "video", note: "\"In My Feelings\", July." },
    { label: "This Is America", kind: "youtube", icon: "video", note: "May." },
    { label: "YouTube Rewind 2018 becomes the most-disliked video", kind: "youtube", icon: "video" },
    { label: "Cambridge Analytica and GDPR", kind: "event", icon: "lock", note: "March and May; privacy enters the vocabulary." },
  ],
  tech: [
    { label: "iPhone XS, XS Max, and XR", kind: "phone", icon: "iphone" },
    { label: "Apple Watch Series 4", kind: "device", icon: "watch", note: "ECG and fall detection." },
    { label: "iPad Pro with USB-C and the new MacBook Air", kind: "device", icon: "tablet" },
    { label: "macOS Mojave dark mode", kind: "computer", icon: "moon" },
    { label: "Google Pixel 3 and Duplex demo", kind: "phone", icon: "phone" },
    { label: "Falcon Heavy launches a Tesla", kind: "event", icon: "rocket", note: "February 6." },
    { label: "Oculus Go", kind: "device", icon: "headset" },
    { label: "Spotify IPO", kind: "event", icon: "music", note: "April." },
  ],
  games: [
    { label: "Fortnite on mobile and Switch", kind: "game", icon: "controller", note: "April and June." },
    { label: "Fortnite rocket launch", kind: "game", icon: "rocket", note: "June 30; the first live event." },
    { label: "Red Dead Redemption 2", kind: "game", icon: "controller", note: "October 26." },
    { label: "God of War", kind: "game", icon: "playstation", note: "April 20." },
    { label: "Marvel's Spider-Man", kind: "game", icon: "playstation" },
    { label: "Super Smash Bros. Ultimate", kind: "game", icon: "switch", note: "December 7; everyone is here." },
    { label: "Pokémon: Let's Go, Pikachu! and Eevee!", kind: "game", icon: "switch" },
    { label: "Celeste and Dead Cells", kind: "game", icon: "switch" },
    { label: "Among Us released", kind: "game", icon: "phone", note: "June; it became a phenomenon in 2020." },
    { label: "PUBG Mobile and Black Ops 4 Blackout", kind: "game", icon: "phone" },
    { label: "Beat Saber", kind: "game", icon: "headset" },
  ],
  onScreen: [
    { label: "Black Panther", kind: "movie", icon: "film", note: "February." },
    { label: "Avengers: Infinity War", kind: "movie", icon: "film", note: "April; the snap." },
    { label: "Spider-Man: Into the Spider-Verse", kind: "movie", icon: "film", note: "December." },
    { label: "Incredibles 2", kind: "movie", icon: "film" },
    { label: "Bohemian Rhapsody and A Star Is Born", kind: "movie", icon: "music" },
    { label: "Deadpool 2 and Aquaman", kind: "movie", icon: "film" },
    { label: "Bird Box", kind: "movie", icon: "stream", note: "December, Netflix." },
    { label: "Black Mirror: Bandersnatch", kind: "movie", icon: "stream", note: "December 28; choose your own path." },
    { label: "Cobra Kai premieres", kind: "show", icon: "video", note: "On YouTube Red, May." },
    { label: "Queer Eye and The Haunting of Hill House", kind: "show", icon: "stream" },
    { label: "Succession and Killing Eve premiere", kind: "show", icon: "tv" },
  ],
  music: [
    { id: "c2018-godsplan", title: "God's Plan", artist: "Drake" },
    { id: "c2018-inmyfeelings", title: "In My Feelings", artist: "Drake" },
    { id: "c2018-sad", title: "SAD!", artist: "XXXTentacion" },
    { id: "c2018-luciddreams", title: "Lucid Dreams", artist: "Juice WRLD" },
    { id: "c2018-sickomode", title: "SICKO MODE", artist: "Travis Scott" },
    { id: "c2018-thankunext", title: "thank u, next", artist: "Ariana Grande" },
    { id: "c2018-sunflower", title: "Sunflower", artist: "Post Malone & Swae Lee" },
    { id: "c2018-shallow", title: "Shallow", artist: "Lady Gaga & Bradley Cooper" },
    { id: "c2018-girlslikeyou", title: "Girls Like You", artist: "Maroon 5 ft. Cardi B" },
    { id: "c2018-thisisamerica", title: "This Is America", artist: "Childish Gambino" },
  ],
  culture: [
    { label: "Fortnite dances", kind: "trend", icon: "music", note: "Floss, Orange Justice, Take the L." },
    { label: "Baby Shark", kind: "trend", icon: "music", note: "Doo doo doo doo doo doo." },
    { label: "Hydro Flasks and Crocs' comeback", kind: "fashion", icon: "star" },
    { label: "Fila Disruptors and chunky sneakers", kind: "fashion", icon: "star" },
    { label: "Slime and squishies", kind: "toy", icon: "toy" },
    { label: "Winter Olympics in Pyeongchang", kind: "event", icon: "snow" },
    { label: "World Cup in Russia", kind: "event", icon: "trophy", note: "France won." },
    { label: "\"Weird flex but ok\", \"big mood\"", kind: "slang", icon: "smile" },
  ],
  capsule: [
    { label: "Fortnite llama", icon: "gift" },
    { label: "Infinity Gauntlet", icon: "sparkle" },
    { label: "TikTok note", icon: "music" },
    { label: "Smash invitation", icon: "mail" },
    { label: "Dark mode toggle", icon: "moon" },
    { label: "Hydro Flask", icon: "cloud" },
  ],
};
