import type { CultureYearInput } from "@/lib/content/schema";

/** 2019 — CULTURAL CONTEXT (general history, not personal). */
export const culture2019: CultureYearInput = {
  year: 2019,
  headline: "Old Town Road, a black hole, and Baby Yoda.",
  blurb:
    "TikTok broke through worldwide, Old Town Road spent a record nineteen weeks at number one, and Fortnite ended a chapter by swallowing its own map. Disney+ launched in November with The Mandalorian, Avengers: Endgame became the biggest film ever, and Minecraft came roaring back on YouTube.",
  design:
    "iOS 13 dark mode, neumorphism on Dribbble, and Disney+'s glossy blue tiles. Vertical video and TikTok's bottom-nav layout became the new default.",
  internet: [
    { label: "TikTok goes global", kind: "app", icon: "music", note: "The Renegade dance and Charli D'Amelio's rise by the fall." },
    { label: "PewDiePie vs T-Series", kind: "youtube", icon: "video", note: "The subscriber race ended in April." },
    { label: "Minecraft's comeback", kind: "youtube", icon: "lego", note: "PewDiePie's series in June pulled everyone back in." },
    { label: "Area 51 raid", kind: "meme", icon: "rocket", note: "\"They can't stop all of us.\" September 20." },
    { label: "Baby Yoda", kind: "meme", icon: "smile", note: "November 12." },
    { label: "\"OK Boomer\"", kind: "slang", icon: "smile", note: "October." },
    { label: "Woman yelling at a cat", kind: "meme", icon: "smile" },
    { label: "VSCO girls", kind: "trend", icon: "camera", note: "Scrunchies, Hydro Flasks, \"and I oop\", sksksk." },
    { label: "\"Ight imma head out\"", kind: "meme", icon: "smile", note: "August." },
    { label: "Keanu Reeves: \"You're breathtaking\"", kind: "meme", icon: "video", note: "E3, June." },
    { label: "Snapchat's gender-swap filter", kind: "app", icon: "ghost", note: "May." },
    { label: "Fortnite World Cup", kind: "event", icon: "trophy", note: "July; Bugha won $3 million at 16." },
  ],
  tech: [
    { label: "Disney+", kind: "app", icon: "stream", note: "November 12." },
    { label: "Apple TV+ and Apple Arcade", kind: "app", icon: "stream", note: "November 1 and September 19." },
    { label: "AirPods Pro", kind: "device", icon: "earbuds", note: "October 30." },
    { label: "iPhone 11 and 11 Pro", kind: "phone", icon: "iphone", note: "Three cameras and Night mode." },
    { label: "iOS 13 dark mode", kind: "app", icon: "moon" },
    { label: "Nintendo Switch Lite", kind: "console", icon: "switch", note: "September." },
    { label: "Google Stadia", kind: "console", icon: "cloud", note: "November; cloud gaming's first big swing." },
    { label: "Samsung Galaxy Fold", kind: "phone", icon: "phone" },
    { label: "First image of a black hole", kind: "event", icon: "moon", note: "April 10." },
  ],
  games: [
    { label: "Fortnite: The End and Chapter 2", kind: "game", icon: "controller", note: "October 13; the black hole." },
    { label: "Apex Legends", kind: "game", icon: "controller", note: "February 4; surprise launch." },
    { label: "Minecraft resurgence", kind: "game", icon: "lego" },
    { label: "Pokémon Sword and Shield", kind: "game", icon: "switch", note: "November 15." },
    { label: "Untitled Goose Game", kind: "game", icon: "bird", note: "September." },
    { label: "Call of Duty: Modern Warfare (2019) and Call of Duty Mobile", kind: "game", icon: "phone" },
    { label: "Sekiro and Resident Evil 2", kind: "game", icon: "playstation" },
    { label: "Luigi's Mansion 3 and Super Mario Maker 2", kind: "game", icon: "switch" },
    { label: "Death Stranding and Control", kind: "game", icon: "playstation" },
    { label: "Kingdom Hearts III and Fire Emblem: Three Houses", kind: "game", icon: "switch" },
    { label: "Roblox keeps growing", kind: "game", icon: "lego", note: "Adopt Me! and a new generation of builders." },
  ],
  onScreen: [
    { label: "Avengers: Endgame", kind: "movie", icon: "film", note: "April 26; the biggest film ever at the time." },
    { label: "The Mandalorian premieres", kind: "show", icon: "stream", note: "November 12." },
    { label: "Game of Thrones ends", kind: "show", icon: "tv", note: "May 19." },
    { label: "Stranger Things 3", kind: "show", icon: "stream", note: "July 4." },
    { label: "Toy Story 4 and Frozen II", kind: "movie", icon: "film" },
    { label: "Spider-Man: Far From Home", kind: "movie", icon: "film" },
    { label: "Joker and Parasite", kind: "movie", icon: "film" },
    { label: "The Lion King and Aladdin", kind: "movie", icon: "film" },
    { label: "Euphoria and The Boys premiere", kind: "show", icon: "tv" },
    { label: "Chernobyl", kind: "show", icon: "tv" },
    { label: "Detective Pikachu", kind: "movie", icon: "film" },
    { label: "Star Wars: The Rise of Skywalker", kind: "movie", icon: "rocket" },
  ],
  music: [
    { id: "c2019-oldtownroad", title: "Old Town Road", artist: "Lil Nas X ft. Billy Ray Cyrus" },
    { id: "c2019-badguy", title: "bad guy", artist: "Billie Eilish" },
    { id: "c2019-7rings", title: "7 rings", artist: "Ariana Grande" },
    { id: "c2019-sunflower", title: "Sunflower", artist: "Post Malone & Swae Lee" },
    { id: "c2019-truthhurts", title: "Truth Hurts", artist: "Lizzo" },
    { id: "c2019-senorita", title: "Señorita", artist: "Shawn Mendes & Camila Cabello" },
    { id: "c2019-sucker", title: "Sucker", artist: "Jonas Brothers" },
    { id: "c2019-circles", title: "Circles", artist: "Post Malone" },
    { id: "c2019-dancemonkey", title: "Dance Monkey", artist: "Tones and I" },
    { id: "c2019-someoneyouloved", title: "Someone You Loved", artist: "Lewis Capaldi" },
  ],
  culture: [
    { label: "TikTok dances", kind: "trend", icon: "music", note: "Renegade, Say So, Savage." },
    { label: "VSCO girl starter pack", kind: "fashion", icon: "camera" },
    { label: "Air Force 1s and Nike Tech", kind: "fashion", icon: "star" },
    { label: "Chicken sandwich wars", kind: "food", icon: "pizza", note: "Popeyes, August." },
    { label: "Baby Shark at the World Series", kind: "trend", icon: "ball" },
    { label: "Women's World Cup", kind: "event", icon: "trophy", note: "The USWNT won in July." },
    { label: "Lil Nas X and Billie Eilish", kind: "trend", icon: "music" },
    { label: "\"Tea\", \"periodt\", \"no cap\"", kind: "slang", icon: "smile" },
  ],
  capsule: [
    { label: "Cowboy hat", icon: "star" },
    { label: "Black hole", icon: "moon" },
    { label: "Baby Yoda", icon: "smile" },
    { label: "AirPods Pro", icon: "earbuds" },
    { label: "Scrunchie", icon: "sparkle" },
    { label: "Disney+", icon: "stream" },
  ],
};
