import type { CultureYearInput } from "@/lib/content/schema";

/** 2020 — CULTURAL CONTEXT (general history, not personal). */
export const culture2020: CultureYearInput = {
  year: 2020,
  headline: "You're on mute.",
  blurb:
    "The pandemic sent school, work, and friendships onto Zoom, Discord, and FaceTime in March. Animal Crossing, Among Us, and Fall Guys became shared living rooms, TikTok defined the year's music, and the PlayStation 5 and Xbox Series X arrived in November to a world stuck at home.",
  design:
    "iOS 14 widgets and custom home screens, macOS Big Sur's rounded icons, Zoom's grid, and Reels' vertical feed. Glassmorphism became the design word of late 2020.",
  internet: [
    { label: "Zoom becomes a verb", kind: "app", icon: "video", note: "School and everything else, from March." },
    { label: "Among Us takes over", kind: "game", icon: "phone", note: "August–September; \"sus\" enters the language." },
    { label: "TikTok's biggest year", kind: "app", icon: "music", note: "Savage, Say So, and the Blinding Lights challenge." },
    { label: "Instagram Reels and YouTube Shorts launch", kind: "app", icon: "reel", note: "August and September." },
    { label: "Tiger King", kind: "show", icon: "stream", note: "March 20; the first lockdown obsession." },
    { label: "Dalgona coffee and banana bread", kind: "trend", icon: "pizza" },
    { label: "Dream's Minecraft Manhunt", kind: "youtube", icon: "lego" },
    { label: "Travis Scott's Fortnite concert", kind: "event", icon: "music", note: "April 23; 12 million players." },
    { label: "Ratatouille the TikTok Musical", kind: "trend", icon: "music", note: "November–December." },
    { label: "\"How it started / how it's going\"", kind: "meme", icon: "smile" },
    { label: "Sea shanties", kind: "meme", icon: "music", note: "December into January 2021." },
    { label: "Clubhouse and Houseparty", kind: "app", icon: "chat" },
  ],
  tech: [
    { label: "PlayStation 5", kind: "console", icon: "playstation", note: "November 12; impossible to buy." },
    { label: "Xbox Series X and S", kind: "console", icon: "xbox", note: "November 10." },
    { label: "iPhone 12 and MagSafe", kind: "phone", icon: "iphone", note: "October; 5G." },
    { label: "Apple Silicon M1", kind: "computer", icon: "laptop", note: "November 10." },
    { label: "iOS 14 home screen customisation", kind: "app", icon: "iphone" },
    { label: "Oculus Quest 2", kind: "device", icon: "headset", note: "October." },
    { label: "Chromebooks for remote school", kind: "computer", icon: "laptop" },
    { label: "SpaceX Crew Dragon", kind: "event", icon: "rocket", note: "May 30; astronauts from US soil again." },
    { label: "AirPods Max and HomePod mini", kind: "device", icon: "headphones" },
  ],
  games: [
    { label: "Animal Crossing: New Horizons", kind: "game", icon: "leaf", note: "March 20; the lockdown island." },
    { label: "Among Us", kind: "game", icon: "phone" },
    { label: "Fall Guys", kind: "game", icon: "controller", note: "August." },
    { label: "Call of Duty: Warzone", kind: "game", icon: "controller", note: "March 10." },
    { label: "Valorant", kind: "game", icon: "desktop", note: "June." },
    { label: "Genshin Impact", kind: "game", icon: "phone", note: "September." },
    { label: "The Last of Us Part II and Ghost of Tsushima", kind: "game", icon: "playstation" },
    { label: "Hades", kind: "game", icon: "switch", note: "September." },
    { label: "Cyberpunk 2077", kind: "game", icon: "desktop", note: "December; a rough launch." },
    { label: "Phasmophobia", kind: "game", icon: "ghost" },
    { label: "Spider-Man: Miles Morales and Demon's Souls", kind: "game", icon: "playstation" },
    { label: "Roblox: Piggy and Adopt Me!", kind: "game", icon: "lego" },
  ],
  onScreen: [
    { label: "Tiger King", kind: "show", icon: "stream" },
    { label: "The Last Dance", kind: "show", icon: "ball", note: "April–May." },
    { label: "The Queen's Gambit", kind: "show", icon: "stream", note: "October." },
    { label: "The Mandalorian season 2", kind: "show", icon: "stream" },
    { label: "Hamilton on Disney+", kind: "movie", icon: "mic", note: "July 3." },
    { label: "Avatar: The Last Airbender on Netflix", kind: "show", icon: "stream", note: "May." },
    { label: "Soul and Wonder Woman 1984", kind: "movie", icon: "film", note: "Christmas Day, streaming." },
    { label: "Ted Lasso premieres", kind: "show", icon: "tv", note: "August." },
    { label: "Outer Banks and Never Have I Ever", kind: "show", icon: "stream" },
    { label: "Cobra Kai moves to Netflix", kind: "show", icon: "stream" },
    { label: "Bridgerton", kind: "show", icon: "stream", note: "December 25." },
    { label: "Sonic the Hedgehog and Onward", kind: "movie", icon: "film", note: "The last films before cinemas closed." },
  ],
  music: [
    { id: "c2020-blindinglights", title: "Blinding Lights", artist: "The Weeknd" },
    { id: "c2020-thebox", title: "The Box", artist: "Roddy Ricch" },
    { id: "c2020-sayso", title: "Say So", artist: "Doja Cat" },
    { id: "c2020-dontstartnow", title: "Don't Start Now", artist: "Dua Lipa" },
    { id: "c2020-watermelon", title: "Watermelon Sugar", artist: "Harry Styles" },
    { id: "c2020-savagelove", title: "Savage Love", artist: "Jawsh 685 & Jason Derulo" },
    { id: "c2020-wap", title: "WAP", artist: "Cardi B ft. Megan Thee Stallion" },
    { id: "c2020-dynamite", title: "Dynamite", artist: "BTS" },
    { id: "c2020-mood", title: "Mood", artist: "24kGoldn ft. iann dior" },
    { id: "c2020-cardigan", title: "cardigan", artist: "Taylor Swift" },
  ],
  culture: [
    { label: "Lockdown", kind: "event", icon: "house", note: "Masks, six feet, and \"unprecedented times\"." },
    { label: "Zoom school", kind: "trend", icon: "laptop" },
    { label: "Sweatpants and tie-dye", kind: "fashion", icon: "star" },
    { label: "Cottagecore", kind: "trend", icon: "leaf" },
    { label: "Kobe Bryant dies", kind: "event", icon: "ball", note: "January 26." },
    { label: "A summer of protests", kind: "event", icon: "flag", note: "June." },
    { label: "A US election year", kind: "event", icon: "flag", note: "November 3; counted for days." },
    { label: "Murder hornets and \"nature is healing\"", kind: "meme", icon: "bug" },
    { label: "PS5 restocks", kind: "trend", icon: "playstation" },
    { label: "\"Simp\", \"sus\", \"it's the ___ for me\"", kind: "slang", icon: "smile" },
  ],
  capsule: [
    { label: "Face mask", icon: "smile" },
    { label: "Zoom grid", icon: "video" },
    { label: "Among Us crewmate", icon: "ghost" },
    { label: "Tom Nook", icon: "leaf" },
    { label: "PS5", icon: "playstation" },
    { label: "Sourdough", icon: "pizza" },
  ],
};
