import type { CultureYearInput } from "@/lib/content/schema";

/** 2021 — CULTURAL CONTEXT (general history, not personal). */
export const culture2021: CultureYearInput = {
  year: 2021,
  headline: "Drivers license, Squid Game, and a boat stuck in a canal.",
  blurb:
    "Vaccines rolled out and life came back in pieces. Squid Game became Netflix's biggest series, Facebook renamed itself Meta, NFTs and GameStop stock became internet spectacles, and Windows 11 and the M1 MacBook Pros set the look of the next few years.",
  design:
    "Windows 11's rounded corners and Mica glass, iOS 15, and the return of gradients. Y2K nostalgia became a design trend; 'glassmorphism' shipped in real products.",
  internet: [
    { label: "Squid Game", kind: "show", icon: "stream", note: "September 17; Netflix's most-watched series." },
    { label: "Facebook becomes Meta", kind: "site", icon: "globe", note: "October 28; \"the metaverse\"." },
    { label: "GameStop and r/wallstreetbets", kind: "event", icon: "key", note: "January." },
    { label: "NFTs", kind: "trend", icon: "sparkle", note: "Beeple's $69 million sale in March; Bored Apes by April." },
    { label: "Wordle", kind: "game", icon: "keyboard", note: "Released in October; the green squares spread in December." },
    { label: "Bernie's mittens", kind: "meme", icon: "snow", note: "January 20." },
    { label: "Ever Given stuck in the Suez Canal", kind: "meme", icon: "map", note: "March 23–29." },
    { label: "\"I'm not a cat\" Zoom lawyer", kind: "meme", icon: "video", note: "February 9." },
    { label: "Facebook, Instagram, and WhatsApp go down", kind: "event", icon: "wifi", note: "October 4, for six hours." },
    { label: "Bo Burnham: Inside", kind: "youtube", icon: "video", note: "May 30; \"Welcome to the Internet\"." },
    { label: "\"Cheugy\", \"sheesh\", \"bussin\"", kind: "slang", icon: "smile" },
    { label: "Devious licks and the milk crate challenge", kind: "meme", icon: "video", note: "August–September on TikTok." },
  ],
  tech: [
    { label: "Windows 11", kind: "computer", icon: "window", note: "October 5." },
    { label: "MacBook Pro 14 and 16 (M1 Pro/Max)", kind: "computer", icon: "laptop", note: "October; ports came back." },
    { label: "iPhone 13", kind: "phone", icon: "iphone" },
    { label: "Colourful M1 iMac and AirTag", kind: "computer", icon: "desktop", note: "April." },
    { label: "Nintendo Switch OLED", kind: "console", icon: "switch", note: "October 8." },
    { label: "Steam Deck announced", kind: "console", icon: "controller", note: "July; shipped February 2022." },
    { label: "Perseverance and Ingenuity on Mars", kind: "event", icon: "rocket", note: "February 18." },
    { label: "Billionaires in space", kind: "event", icon: "rocket", note: "July; Blue Origin and Virgin Galactic." },
    { label: "Chip shortages", kind: "event", icon: "battery", note: "Consoles, cars, and GPUs all scarce." },
  ],
  games: [
    { label: "Valheim", kind: "game", icon: "desktop", note: "February." },
    { label: "It Takes Two", kind: "game", icon: "controller", note: "March; Game of the Year." },
    { label: "Metroid Dread", kind: "game", icon: "switch", note: "October." },
    { label: "Halo Infinite and Forza Horizon 5", kind: "game", icon: "xbox", note: "November–December." },
    { label: "Pokémon Brilliant Diamond and Shining Pearl", kind: "game", icon: "switch" },
    { label: "Resident Evil Village and Returnal", kind: "game", icon: "playstation" },
    { label: "Ratchet & Clank: Rift Apart", kind: "game", icon: "playstation" },
    { label: "Friday Night Funkin'", kind: "game", icon: "music" },
    { label: "Fortnite Chapter 3", kind: "game", icon: "controller", note: "December; the island flipped." },
    { label: "Inscryption and Unpacking", kind: "game", icon: "desktop" },
    { label: "Roblox goes public", kind: "game", icon: "lego", note: "March." },
    { label: "Pokémon Unite and New Pokémon Snap", kind: "game", icon: "switch" },
  ],
  onScreen: [
    { label: "Spider-Man: No Way Home", kind: "movie", icon: "film", note: "December 17." },
    { label: "Dune", kind: "movie", icon: "film", note: "October." },
    { label: "Encanto", kind: "movie", icon: "music", note: "November; \"We Don't Talk About Bruno\" peaked in January 2022." },
    { label: "Shang-Chi and Eternals", kind: "movie", icon: "film" },
    { label: "WandaVision, Loki, and Hawkeye", kind: "show", icon: "stream" },
    { label: "Arcane", kind: "show", icon: "stream", note: "November." },
    { label: "Ted Lasso season 2 and Succession season 3", kind: "show", icon: "tv" },
    { label: "The White Lotus and Mare of Easttown", kind: "show", icon: "tv" },
    { label: "Invincible", kind: "show", icon: "stream" },
    { label: "Only Murders in the Building", kind: "show", icon: "tv" },
    { label: "Free Guy and Godzilla vs. Kong", kind: "movie", icon: "film" },
    { label: "Luca and The Mitchells vs. the Machines", kind: "movie", icon: "stream" },
  ],
  music: [
    { id: "c2021-driverslicense", title: "drivers license", artist: "Olivia Rodrigo" },
    { id: "c2021-good4u", title: "good 4 u", artist: "Olivia Rodrigo" },
    { id: "c2021-montero", title: "MONTERO (Call Me by Your Name)", artist: "Lil Nas X" },
    { id: "c2021-industrybaby", title: "Industry Baby", artist: "Lil Nas X & Jack Harlow" },
    { id: "c2021-stay", title: "STAY", artist: "The Kid LAROI & Justin Bieber" },
    { id: "c2021-levitating", title: "Levitating", artist: "Dua Lipa" },
    { id: "c2021-butter", title: "Butter", artist: "BTS" },
    { id: "c2021-kissmemore", title: "Kiss Me More", artist: "Doja Cat ft. SZA" },
    { id: "c2021-heatwaves", title: "Heat Waves", artist: "Glass Animals" },
    { id: "c2021-easyonme", title: "Easy on Me", artist: "Adele" },
    { id: "c2021-alltoowell", title: "All Too Well (10 Minute Version)", artist: "Taylor Swift" },
  ],
  culture: [
    { label: "Vaccines and reopening", kind: "event", icon: "sun" },
    { label: "Tokyo Olympics (held in 2021)", kind: "event", icon: "trophy" },
    { label: "Y2K fashion revival", kind: "fashion", icon: "star", note: "Low-rise, baggy jeans, butterfly clips." },
    { label: "Crypto and Dogecoin", kind: "trend", icon: "key" },
    { label: "Squid Game Halloween costumes", kind: "trend", icon: "smile" },
    { label: "Red (Taylor's Version)", kind: "trend", icon: "music" },
    { label: "Pop-Its and fidget toys", kind: "toy", icon: "toy" },
    { label: "\"Main character energy\"", kind: "slang", icon: "smile" },
    { label: "Hybrid everything", kind: "trend", icon: "laptop" },
  ],
  capsule: [
    { label: "Wordle grid", icon: "keyboard" },
    { label: "Squid Game shape", icon: "sparkle" },
    { label: "Mittens", icon: "snow" },
    { label: "Container ship", icon: "map" },
    { label: "M1 chip", icon: "laptop" },
    { label: "Vaccine card", icon: "ticket" },
  ],
};
