import type { CultureYearInput } from "@/lib/content/schema";

/** 2022 — CULTURAL CONTEXT (general history, not personal). */
export const culture2022: CultureYearInput = {
  year: 2022,
  headline: "Elden Ring, Wordle, and a chatbot in November.",
  blurb:
    "Wordle went to the New York Times in January and Elden Ring arrived in February. Top Gun: Maverick brought cinemas back, Stranger Things 4 sent Kate Bush to number one, BeReal briefly beat Instagram, Twitter changed hands in October, and ChatGPT launched on November 30.",
  design:
    "iOS 16's lock screen and the Dynamic Island. AI-generated images everywhere after DALL·E 2, Midjourney, and Stable Diffusion. Bento grids and glass in Apple's keynotes.",
  internet: [
    { label: "Wordle", kind: "game", icon: "keyboard", note: "Bought by the New York Times on January 31." },
    { label: "ChatGPT launches", kind: "app", icon: "ai", note: "November 30." },
    { label: "DALL·E 2, Midjourney, Stable Diffusion", kind: "app", icon: "ai", note: "Generated images flooded feeds from July." },
    { label: "BeReal", kind: "app", icon: "camera", note: "Two minutes to post; App of the Year." },
    { label: "Twitter sold to Elon Musk", kind: "site", icon: "bird", note: "October 27." },
    { label: "Stranger Things 4 and Running Up That Hill", kind: "meme", icon: "music", note: "May 27 and July 1." },
    { label: "Gentleminions", kind: "meme", icon: "video", note: "July; suits at the Minions movie." },
    { label: "\"It's corn\"", kind: "meme", icon: "leaf", note: "August." },
    { label: "Little Miss memes", kind: "meme", icon: "smile", note: "July." },
    { label: "Wednesday dance", kind: "meme", icon: "music", note: "November." },
    { label: "Morbin' time", kind: "meme", icon: "film", note: "June." },
    { label: "Crypto and FTX collapse", kind: "event", icon: "key", note: "May and November." },
    { label: "Spotify Wrapped as an annual event", kind: "trend", icon: "music" },
  ],
  tech: [
    { label: "iPhone 14 Pro and the Dynamic Island", kind: "phone", icon: "iphone", note: "September." },
    { label: "Apple Watch Ultra and AirPods Pro 2", kind: "device", icon: "watch" },
    { label: "Steam Deck ships", kind: "console", icon: "controller", note: "February 25." },
    { label: "M2 MacBook Air and Mac Studio", kind: "computer", icon: "laptop" },
    { label: "iOS 16 lock screen", kind: "app", icon: "iphone" },
    { label: "Nothing Phone (1)", kind: "phone", icon: "phone", note: "July; lights on the back." },
    { label: "Meta Quest Pro", kind: "device", icon: "headset", note: "October." },
    { label: "Netflix with ads", kind: "app", icon: "stream", note: "November." },
    { label: "Microsoft announces the Activision Blizzard deal", kind: "event", icon: "xbox", note: "January 18; $68.7 billion." },
  ],
  games: [
    { label: "Elden Ring", kind: "game", icon: "controller", note: "February 25; Game of the Year." },
    { label: "God of War Ragnarök", kind: "game", icon: "playstation", note: "November 9." },
    { label: "Pokémon Legends: Arceus", kind: "game", icon: "switch", note: "January 28." },
    { label: "Pokémon Scarlet and Violet", kind: "game", icon: "switch", note: "November 18; open world, rough edges." },
    { label: "Splatoon 3 and Kirby and the Forgotten Land", kind: "game", icon: "switch" },
    { label: "Stray", kind: "game", icon: "playstation", note: "July; you are a cat." },
    { label: "Overwatch 2 and Modern Warfare II", kind: "game", icon: "controller", note: "October." },
    { label: "Vampire Survivors and Cult of the Lamb", kind: "game", icon: "desktop" },
    { label: "Fortnite Zero Build", kind: "game", icon: "controller", note: "March." },
    { label: "Marvel Snap", kind: "game", icon: "phone", note: "October." },
    { label: "Horizon Forbidden West and Xenoblade Chronicles 3", kind: "game", icon: "playstation" },
    { label: "Nintendo Switch Sports", kind: "game", icon: "switch", note: "April." },
  ],
  onScreen: [
    { label: "Top Gun: Maverick", kind: "movie", icon: "plane", note: "May 27." },
    { label: "Avatar: The Way of Water", kind: "movie", icon: "film", note: "December 16." },
    { label: "Stranger Things 4", kind: "show", icon: "stream" },
    { label: "Wednesday", kind: "show", icon: "stream", note: "November 23." },
    { label: "House of the Dragon and The Rings of Power", kind: "show", icon: "tv", note: "August and September." },
    { label: "The Bear", kind: "show", icon: "tv", note: "June." },
    { label: "Severance and Andor", kind: "show", icon: "stream" },
    { label: "Everything Everywhere All at Once", kind: "movie", icon: "film", note: "March." },
    { label: "The Batman and Black Panther: Wakanda Forever", kind: "movie", icon: "film" },
    { label: "Minions: The Rise of Gru and Puss in Boots: The Last Wish", kind: "movie", icon: "film" },
    { label: "Euphoria season 2", kind: "show", icon: "tv", note: "January." },
    { label: "Heartstopper and Cyberpunk: Edgerunners", kind: "show", icon: "stream" },
  ],
  music: [
    { id: "c2022-asitwas", title: "As It Was", artist: "Harry Styles" },
    { id: "c2022-heatwaves", title: "Heat Waves", artist: "Glass Animals" },
    { id: "c2022-antihero", title: "Anti-Hero", artist: "Taylor Swift" },
    { id: "c2022-aboutdamntime", title: "About Damn Time", artist: "Lizzo" },
    { id: "c2022-runningupthathill", title: "Running Up That Hill", artist: "Kate Bush" },
    { id: "c2022-badhabit", title: "Bad Habit", artist: "Steve Lacy" },
    { id: "c2022-unholy", title: "Unholy", artist: "Sam Smith & Kim Petras" },
    { id: "c2022-firstclass", title: "First Class", artist: "Jack Harlow" },
    { id: "c2022-titimepregunto", title: "Tití Me Preguntó", artist: "Bad Bunny" },
    { id: "c2022-breakmysoul", title: "Break My Soul", artist: "Beyoncé" },
    { id: "c2022-killbill", title: "Kill Bill", artist: "SZA", note: "December; owned early 2023." },
  ],
  culture: [
    { label: "World Cup in Qatar", kind: "event", icon: "trophy", note: "Argentina and Messi, December 18." },
    { label: "The Eras Tour ticket meltdown", kind: "event", icon: "ticket", note: "November." },
    { label: "Barbiecore and clean girl", kind: "fashion", icon: "star" },
    { label: "New Balance 550s and Crocs with Jibbitz", kind: "fashion", icon: "star" },
    { label: "\"Goblin mode\" and \"quiet quitting\"", kind: "slang", icon: "smile" },
    { label: "The Will Smith slap", kind: "event", icon: "film", note: "March 27." },
    { label: "Queen Elizabeth II dies", kind: "event", icon: "flag", note: "September 8." },
    { label: "Inflation and gas prices", kind: "event", icon: "car" },
    { label: "\"Rizz\" and \"Ohio\" begin", kind: "slang", icon: "smile" },
  ],
  capsule: [
    { label: "Wordle tile", icon: "keyboard" },
    { label: "Elden Ring", icon: "controller" },
    { label: "Dynamic Island", icon: "iphone" },
    { label: "BeReal alert", icon: "camera" },
    { label: "Chat bubble", icon: "ai" },
    { label: "Steam Deck", icon: "controller" },
  ],
};
