import type { CultureYearInput } from "@/lib/content/schema";

/** 2023 — CULTURAL CONTEXT (general history, not personal). */
export const culture2023: CultureYearInput = {
  year: 2023,
  headline: "Barbenheimer, the Eras Tour, and everyone talking to an AI.",
  blurb:
    "ChatGPT hit 100 million users in January and GPT-4 arrived in March. Barbie and Oppenheimer opened the same July weekend, Taylor Swift's Eras Tour became the biggest ever, Tears of the Kingdom and Baldur's Gate 3 defined gaming, and Hollywood's writers and actors went on strike for months.",
  design:
    "Apple Vision Pro's 'spatial computing' and visionOS glass. iOS 17 StandBy, USB-C on iPhone, and AI-generated imagery as a normal part of the feed.",
  internet: [
    { label: "ChatGPT hits 100 million users", kind: "app", icon: "ai", note: "January; GPT-4 followed on March 14." },
    { label: "Threads launches", kind: "app", icon: "at", note: "July 5; 100 million sign-ups in five days." },
    { label: "Twitter becomes X", kind: "site", icon: "bird", note: "July 24." },
    { label: "Barbenheimer", kind: "meme", icon: "film", note: "July 21." },
    { label: "The Roman Empire", kind: "meme", icon: "smile", note: "September." },
    { label: "Girl dinner and girl math", kind: "meme", icon: "pizza", note: "Summer." },
    { label: "Grimace Shake", kind: "meme", icon: "video", note: "June." },
    { label: "Skibidi Toilet", kind: "meme", icon: "video", note: "February; a YouTube Shorts series." },
    { label: "\"Rizz\" is Oxford's word of the year", kind: "slang", icon: "smile" },
    { label: "NPC streaming", kind: "meme", icon: "stream", note: "July; \"ice cream so good\"." },
    { label: "The Amazing Digital Circus", kind: "youtube", icon: "video", note: "October 13." },
    { label: "Reddit API protests", kind: "event", icon: "chat", note: "June." },
    { label: "Netflix ends password sharing", kind: "event", icon: "stream", note: "May." },
  ],
  tech: [
    { label: "Apple Vision Pro announced", kind: "device", icon: "headset", note: "June 5." },
    { label: "iPhone 15 with USB-C", kind: "phone", icon: "iphone", note: "September." },
    { label: "M3 MacBook Pro and 15-inch MacBook Air", kind: "computer", icon: "laptop" },
    { label: "Meta Quest 3", kind: "device", icon: "headset", note: "October." },
    { label: "PlayStation Portal and PS5 Slim", kind: "console", icon: "playstation", note: "November." },
    { label: "Steam Deck OLED", kind: "console", icon: "controller", note: "November." },
    { label: "Microsoft closes the Activision deal", kind: "event", icon: "xbox", note: "October 13." },
    { label: "Midjourney v5 and the Pope in a puffer jacket", kind: "app", icon: "ai", note: "March." },
    { label: "iOS 17: StandBy, NameDrop, Journal", kind: "app", icon: "iphone" },
  ],
  games: [
    { label: "The Legend of Zelda: Tears of the Kingdom", kind: "game", icon: "switch", note: "May 12." },
    { label: "Baldur's Gate 3", kind: "game", icon: "desktop", note: "August 3; Game of the Year." },
    { label: "Hogwarts Legacy", kind: "game", icon: "controller", note: "February 10." },
    { label: "Marvel's Spider-Man 2", kind: "game", icon: "playstation", note: "October 20." },
    { label: "Super Mario Bros. Wonder", kind: "game", icon: "switch", note: "October 20." },
    { label: "Resident Evil 4 and Dead Space remakes", kind: "game", icon: "controller" },
    { label: "Fortnite OG", kind: "game", icon: "controller", note: "November; a record 44 million players in a day." },
    { label: "Lego Fortnite, Rocket Racing, Fortnite Festival", kind: "game", icon: "lego", note: "December." },
    { label: "Lethal Company", kind: "game", icon: "desktop", note: "October; the end-of-year co-op hit." },
    { label: "Starfield and Alan Wake 2", kind: "game", icon: "xbox" },
    { label: "Street Fighter 6, Diablo IV, Final Fantasy XVI", kind: "game", icon: "playstation" },
    { label: "Pikmin 4 and Suika Game", kind: "game", icon: "switch" },
    { label: "Counter-Strike 2", kind: "game", icon: "desktop", note: "September." },
    { label: "GTA VI trailer", kind: "game", icon: "video", note: "December 4; 100 million views in a day." },
  ],
  onScreen: [
    { label: "Barbie", kind: "movie", icon: "sparkle", note: "July 21; $1.4 billion." },
    { label: "Oppenheimer", kind: "movie", icon: "film", note: "July 21." },
    { label: "The Super Mario Bros. Movie", kind: "movie", icon: "controller", note: "April 5; $1.36 billion." },
    { label: "Spider-Man: Across the Spider-Verse", kind: "movie", icon: "film", note: "June 2." },
    { label: "The Last of Us", kind: "show", icon: "tv", note: "January." },
    { label: "Succession's final season", kind: "show", icon: "tv", note: "March–May." },
    { label: "The Bear season 2 and Beef", kind: "show", icon: "stream" },
    { label: "One Piece live action and Blue Eye Samurai", kind: "show", icon: "stream" },
    { label: "Guardians of the Galaxy Vol. 3", kind: "movie", icon: "rocket" },
    { label: "Five Nights at Freddy's", kind: "movie", icon: "ghost", note: "October 27." },
    { label: "Wonka, Wish, and The Boy and the Heron", kind: "movie", icon: "film", note: "December." },
    { label: "Jury Duty and Ted Lasso's finale", kind: "show", icon: "tv" },
    { label: "Attack on Titan's finale and Jujutsu Kaisen season 2", kind: "show", icon: "tv" },
  ],
  music: [
    { id: "c2023-flowers", title: "Flowers", artist: "Miley Cyrus" },
    { id: "c2023-killbill", title: "Kill Bill", artist: "SZA" },
    { id: "c2023-lastnight", title: "Last Night", artist: "Morgan Wallen" },
    { id: "c2023-vampire", title: "vampire", artist: "Olivia Rodrigo" },
    { id: "c2023-cruelsummer", title: "Cruel Summer", artist: "Taylor Swift" },
    { id: "c2023-paintthetownred", title: "Paint the Town Red", artist: "Doja Cat" },
    { id: "c2023-fastcar", title: "Fast Car", artist: "Luke Combs" },
    { id: "c2023-whatwasimadefor", title: "What Was I Made For?", artist: "Billie Eilish" },
    { id: "c2023-dancethenight", title: "Dance the Night", artist: "Dua Lipa" },
    { id: "c2023-ellabailasola", title: "Ella Baila Sola", artist: "Eslabon Armado & Peso Pluma" },
    { id: "c2023-water", title: "Water", artist: "Tyla" },
    { id: "c2023-greedy", title: "greedy", artist: "Tate McRae" },
  ],
  culture: [
    { label: "The Eras Tour", kind: "event", icon: "ticket", note: "March through the end of the year; the film in October." },
    { label: "Barbenheimer weekend", kind: "event", icon: "film" },
    { label: "Writers' and actors' strikes", kind: "event", icon: "flag", note: "May–November." },
    { label: "Stanley cups", kind: "product", icon: "cloud", note: "The tumbler took over by December." },
    { label: "Coquette, tomato girl, and beige flags", kind: "trend", icon: "smile" },
    { label: "Ice Spice and Peso Pluma", kind: "trend", icon: "music" },
    { label: "\"Delulu\", \"it's giving\", \"ate\"", kind: "slang", icon: "smile" },
    { label: "Kai Cenat and the \"Fanum tax\"", kind: "slang", icon: "stream" },
    { label: "Pickleball", kind: "sport", icon: "ball" },
    { label: "Messi joins Inter Miami", kind: "event", icon: "ball", note: "July." },
  ],
  capsule: [
    { label: "Pink Barbie box", icon: "sparkle" },
    { label: "Vision Pro", icon: "headset" },
    { label: "Friendship bracelet", icon: "heart" },
    { label: "Stanley cup", icon: "cloud" },
    { label: "Zonai device", icon: "switch" },
    { label: "Chat prompt", icon: "ai" },
  ],
};
