import type { CultureYearInput } from "@/lib/content/schema";

/** 2024 — CULTURAL CONTEXT (general history, not personal). */
export const culture2024: CultureYearInput = {
  year: 2024,
  headline: "Brat summer, a rap beef, and a hippo named Moo Deng.",
  blurb:
    "Kendrick and Drake traded diss tracks until Not Like Us ended it in May, Charli XCX painted the summer lime green, and Sabrina Carpenter and Chappell Roan broke through. Apple Vision Pro shipped, Inside Out 2 became the biggest animated film ever, Wicked and Gladiator II shared November, and \"brain rot\" was Oxford's word of the year.",
  design:
    "Brat green as a colour of the year, iOS 18's tinted icons, the Vision Pro's floating glass, and AI features arriving in every keynote. The bento grid became the default layout for launches.",
  internet: [
    { label: "Kendrick vs. Drake", kind: "event", icon: "mic", note: "March–May; \"Not Like Us\" arrived May 4." },
    { label: "Brat summer", kind: "trend", icon: "sparkle", note: "June; lime green everything." },
    { label: "\"Hawk tuah\"", kind: "meme", icon: "smile", note: "June." },
    { label: "\"Very demure, very mindful\"", kind: "meme", icon: "smile", note: "August." },
    { label: "Moo Deng and Pesto", kind: "meme", icon: "smile", note: "September; a baby hippo and a giant penguin chick." },
    { label: "Chill guy", kind: "meme", icon: "smile", note: "November." },
    { label: "Raygun at the Olympics", kind: "meme", icon: "trophy", note: "August; breaking's debut." },
    { label: "\"Brain rot\" is Oxford's word of the year", kind: "slang", icon: "smile", note: "Skibidi, rizz, sigma, gyat, Fanum tax." },
    { label: "TikTok ban signed into law", kind: "event", icon: "music", note: "April 24; the deadline was January 2025." },
    { label: "Bluesky's surge", kind: "app", icon: "bird", note: "November; 20 million users." },
    { label: "Beast Games", kind: "youtube", icon: "video", note: "December 19 on Prime Video." },
    { label: "Jake Paul vs. Mike Tyson on Netflix", kind: "event", icon: "trophy", note: "November 15." },
    { label: "The CrowdStrike outage", kind: "event", icon: "bug", note: "July 19; blue screens at every airport." },
  ],
  tech: [
    { label: "Apple Vision Pro ships", kind: "device", icon: "headset", note: "February 2." },
    { label: "iPhone 16 and Apple Intelligence", kind: "phone", icon: "iphone", note: "September; AI features arrived in October." },
    { label: "GPT-4o, Gemini, and Claude 3.5", kind: "app", icon: "ai", note: "Voice, vision, and a model race all year." },
    { label: "Google's AI Overviews", kind: "app", icon: "search", note: "May; \"glue on pizza\"." },
    { label: "M4 iPad Pro and the tiny Mac mini", kind: "computer", icon: "tablet" },
    { label: "PS5 Pro", kind: "console", icon: "playstation", note: "November 7." },
    { label: "Rabbit R1 and Humane AI Pin", kind: "device", icon: "ai", note: "Spring; the AI gadgets that flopped." },
    { label: "Nvidia becomes the most valuable company", kind: "event", icon: "desktop", note: "June." },
    { label: "SpaceX catches a Starship booster", kind: "event", icon: "rocket", note: "October 13." },
    { label: "Total solar eclipse and northern lights", kind: "event", icon: "sun", note: "April 8 and May 10." },
    { label: "Bitcoin passes $100,000", kind: "event", icon: "key", note: "December." },
  ],
  games: [
    { label: "Palworld", kind: "game", icon: "desktop", note: "January 19; \"Pokémon with guns\"." },
    { label: "Helldivers 2", kind: "game", icon: "playstation", note: "February 8." },
    { label: "Balatro", kind: "game", icon: "desktop", note: "February 20; poker roguelike, phone addiction." },
    { label: "Elden Ring: Shadow of the Erdtree", kind: "game", icon: "controller", note: "June 21." },
    { label: "Black Myth: Wukong", kind: "game", icon: "controller", note: "August 20." },
    { label: "Astro Bot", kind: "game", icon: "playstation", note: "September 6; Game of the Year." },
    { label: "The Legend of Zelda: Echoes of Wisdom", kind: "game", icon: "switch" },
    { label: "Metaphor: ReFantazio and Silent Hill 2", kind: "game", icon: "playstation", note: "October." },
    { label: "Marvel Rivals", kind: "game", icon: "desktop", note: "December 6." },
    { label: "Indiana Jones and the Great Circle", kind: "game", icon: "xbox", note: "December." },
    { label: "Final Fantasy VII Rebirth and Stellar Blade", kind: "game", icon: "playstation" },
    { label: "Pokémon TCG Pocket", kind: "game", icon: "phone", note: "October 30." },
    { label: "Fortnite OG returns for good", kind: "game", icon: "controller", note: "December 6; Chapter 6 began December 1." },
    { label: "Roblox: Dress to Impress and Fisch", kind: "game", icon: "lego" },
    { label: "Stardew Valley 1.6", kind: "game", icon: "leaf", note: "March." },
    { label: "Concord launches and closes in two weeks", kind: "game", icon: "playstation", note: "August–September." },
  ],
  onScreen: [
    { label: "Inside Out 2", kind: "movie", icon: "film", note: "June 14; $1.7 billion." },
    { label: "Deadpool & Wolverine", kind: "movie", icon: "film", note: "July 26." },
    { label: "Dune: Part Two", kind: "movie", icon: "film", note: "March 1." },
    { label: "Wicked and Gladiator II", kind: "movie", icon: "film", note: "November 22; \"Glicked\"." },
    { label: "Moana 2 and Sonic the Hedgehog 3", kind: "movie", icon: "film" },
    { label: "Shōgun", kind: "show", icon: "tv", note: "February; swept the Emmys." },
    { label: "Fallout", kind: "show", icon: "stream", note: "April 10." },
    { label: "Baby Reindeer and Ripley", kind: "show", icon: "stream", note: "April." },
    { label: "House of the Dragon season 2 and The Boys season 4", kind: "show", icon: "tv", note: "June." },
    { label: "Hazbin Hotel, X-Men '97, Arcane season 2", kind: "show", icon: "stream" },
    { label: "Squid Game season 2", kind: "show", icon: "stream", note: "December 26." },
    { label: "Anora, The Substance, Challengers", kind: "movie", icon: "film" },
    { label: "Beetlejuice Beetlejuice and Alien: Romulus", kind: "movie", icon: "film" },
    { label: "The Penguin and Agatha All Along", kind: "show", icon: "tv", note: "September." },
    { label: "Bluey: The Sign", kind: "show", icon: "tv", note: "April 14." },
  ],
  music: [
    { id: "c2024-espresso", title: "Espresso", artist: "Sabrina Carpenter" },
    { id: "c2024-notlikeus", title: "Not Like Us", artist: "Kendrick Lamar" },
    { id: "c2024-goodluckbabe", title: "Good Luck, Babe!", artist: "Chappell Roan" },
    { id: "c2024-birdsofafeather", title: "BIRDS OF A FEATHER", artist: "Billie Eilish" },
    { id: "c2024-abarsong", title: "A Bar Song (Tipsy)", artist: "Shaboozey" },
    { id: "c2024-beautifulthings", title: "Beautiful Things", artist: "Benson Boone" },
    { id: "c2024-texasholdem", title: "Texas Hold 'Em", artist: "Beyoncé" },
    { id: "c2024-fortnight", title: "Fortnight", artist: "Taylor Swift ft. Post Malone" },
    { id: "c2024-ihadsomehelp", title: "I Had Some Help", artist: "Post Malone ft. Morgan Wallen" },
    { id: "c2024-diewithasmile", title: "Die With a Smile", artist: "Lady Gaga & Bruno Mars" },
    { id: "c2024-apt", title: "APT.", artist: "ROSÉ & Bruno Mars" },
    { id: "c2024-360", title: "360", artist: "Charli xcx" },
    { id: "c2024-toosweet", title: "Too Sweet", artist: "Hozier" },
  ],
  culture: [
    { label: "Paris Olympics", kind: "event", icon: "trophy", note: "July 26–August 11." },
    { label: "Taylor Swift and Travis Kelce", kind: "trend", icon: "heart", note: "The Chiefs won the Super Bowl in February; the Eras Tour ended in December." },
    { label: "Adidas Sambas and jorts", kind: "fashion", icon: "star" },
    { label: "Stanley cups and Sephora kids", kind: "trend", icon: "cloud", note: "January." },
    { label: "Sonny Angels, Jellycats, and Labubu", kind: "toy", icon: "toy" },
    { label: "Run clubs and pickleball", kind: "sport", icon: "ball" },
    { label: "BookTok: Fourth Wing and ACOTAR", kind: "book", icon: "book" },
    { label: "A US election year", kind: "event", icon: "flag", note: "November 5." },
    { label: "The Key Bridge collapse in Baltimore", kind: "event", icon: "map", note: "March 26." },
    { label: "Dodgers beat the Yankees; Ohtani goes 50/50", kind: "event", icon: "ball" },
    { label: "Caitlin Clark's rookie year", kind: "sport", icon: "ball" },
    { label: "\"Aura\", \"crash out\", \"lock in\"", kind: "slang", icon: "smile" },
  ],
  capsule: [
    { label: "Brat green square", icon: "sparkle" },
    { label: "Vision Pro", icon: "headset" },
    { label: "Espresso cup", icon: "pizza" },
    { label: "Moo Deng", icon: "smile" },
    { label: "Olympic rings", icon: "trophy" },
    { label: "Balatro joker", icon: "star" },
  ],
};
