import type { CultureYearInput } from "@/lib/content/schema";

/** 2025 — CULTURAL CONTEXT (general history, not personal). */
export const culture2025: CultureYearInput = {
  year: 2025,
  headline: "Six-seven, Switch 2, and a Netflix cartoon at number one.",
  blurb:
    "The Nintendo Switch 2 launched in June and Hollow Knight: Silksong finally arrived in September. KPop Demon Hunters became Netflix's most-watched film and put \"Golden\" at number one, A Minecraft Movie turned \"chicken jockey\" into a theatre riot, and the Eagles won the Super Bowl to a Kendrick Lamar halftime show. AI video, Labubus, and \"6-7\" defined the feed.",
  design:
    "iOS 26's Liquid Glass: translucent, refractive controls across every Apple device. AI-generated video with sound (Veo 3, Sora 2) became a normal part of the feed. Y2K and 'indie sleaze' nostalgia in fashion.",
  internet: [
    { label: "\"6-7\"", kind: "meme", icon: "smile", note: "From a Skrilla song to every middle school; Dictionary.com's word of the year." },
    { label: "Italian brainrot", kind: "meme", icon: "ai", note: "January–April; Tralalero Tralala and Tung Tung Tung Sahur." },
    { label: "KPop Demon Hunters", kind: "movie", icon: "stream", note: "June 20; Netflix's most-watched film ever." },
    { label: "\"Chicken jockey\"", kind: "meme", icon: "controller", note: "April; A Minecraft Movie screenings got loud." },
    { label: "TikTok goes dark for a night", kind: "event", icon: "music", note: "January 18–19; then months of deadline extensions." },
    { label: "Ghibli-style AI images", kind: "trend", icon: "ai", note: "March; ChatGPT's image generator." },
    { label: "Veo 3 and Sora 2", kind: "app", icon: "video", note: "May and September; AI video with sound, everywhere." },
    { label: "\"Aura farming\" boat kid", kind: "meme", icon: "smile", note: "June–July." },
    { label: "\"Performative male\"", kind: "meme", icon: "book", note: "August; matcha, tote bag, wired headphones." },
    { label: "\"Clanker\"", kind: "slang", icon: "ai", note: "July; the word for robots." },
    { label: "Coldplay kiss cam", kind: "meme", icon: "video", note: "July 16." },
    { label: "The Summer I Turned Pretty finale", kind: "show", icon: "stream", note: "September; Team Conrad." },
    { label: "Love Island USA season 7", kind: "show", icon: "heart", note: "June–July." },
    { label: "Streamer University", kind: "youtube", icon: "stream", note: "May; Kai Cenat's Mafiathon 3 followed in September." },
    { label: "\"Rage bait\" is Oxford's word of the year", kind: "slang", icon: "smile" },
  ],
  tech: [
    { label: "Nintendo Switch 2", kind: "console", icon: "switch", note: "June 5; over ten million sold by September." },
    { label: "iPhone 17 and iPhone Air", kind: "phone", icon: "iphone", note: "September 19." },
    { label: "iOS 26 and Liquid Glass", kind: "app", icon: "iphone", note: "Announced June 9, released September 15." },
    { label: "AirPods Pro 3", kind: "device", icon: "earbuds", note: "Heart rate and live translation." },
    { label: "DeepSeek R1", kind: "app", icon: "ai", note: "January 20; Nvidia fell 17% in a day." },
    { label: "GPT-5, Gemini 3, and Claude Opus 4.5", kind: "app", icon: "ai", note: "August, November, and November." },
    { label: "Nvidia hits $5 trillion", kind: "event", icon: "desktop", note: "October 29." },
    { label: "Xbox Ally and the Steam Machine announcement", kind: "console", icon: "controller", note: "October and November." },
    { label: "Meta Ray-Ban Display glasses", kind: "device", icon: "headset", note: "September." },
    { label: "Tariffs and price hikes", kind: "event", icon: "battery", note: "April; consoles, phones, and everything else." },
    { label: "Pope Leo XIV", kind: "event", icon: "flag", note: "May 8; the first American pope." },
  ],
  games: [
    { label: "Hollow Knight: Silksong", kind: "game", icon: "switch", note: "September 4; six years of waiting." },
    { label: "Clair Obscur: Expedition 33", kind: "game", icon: "controller", note: "April 24; Game of the Year." },
    { label: "Mario Kart World and Donkey Kong Bananza", kind: "game", icon: "switch", note: "June 5 and July 17." },
    { label: "Battlefield 6", kind: "game", icon: "controller", note: "October 10." },
    { label: "Arc Raiders", kind: "game", icon: "desktop", note: "October 30." },
    { label: "Monster Hunter Wilds", kind: "game", icon: "controller", note: "February 28." },
    { label: "Split Fiction", kind: "game", icon: "controller", note: "March 6." },
    { label: "Blue Prince and Oblivion Remastered", kind: "game", icon: "desktop", note: "April." },
    { label: "Ghost of Yōtei", kind: "game", icon: "playstation", note: "October 2." },
    { label: "Pokémon Legends: Z-A", kind: "game", icon: "switch", note: "October 16." },
    { label: "Peak, R.E.P.O., and Schedule I", kind: "game", icon: "desktop", note: "The year's co-op word-of-mouth hits." },
    { label: "Roblox: Grow a Garden and Steal a Brainrot", kind: "game", icon: "lego", note: "Over twenty million concurrent players in June." },
    { label: "Fortnite x The Simpsons, then Chapter 7", kind: "game", icon: "controller", note: "November." },
    { label: "Metroid Prime 4: Beyond", kind: "game", icon: "switch", note: "December 4." },
    { label: "GTA VI delayed to 2026", kind: "game", icon: "video", note: "Twice: May and November." },
    { label: "Dispatch", kind: "game", icon: "desktop", note: "October." },
  ],
  onScreen: [
    { label: "KPop Demon Hunters", kind: "movie", icon: "stream" },
    { label: "A Minecraft Movie", kind: "movie", icon: "lego", note: "April 4." },
    { label: "Sinners", kind: "movie", icon: "film", note: "April 18." },
    { label: "Lilo & Stitch and How to Train Your Dragon", kind: "movie", icon: "film", note: "Live-action summer." },
    { label: "Superman and The Fantastic Four: First Steps", kind: "movie", icon: "film", note: "July." },
    { label: "F1", kind: "movie", icon: "car", note: "June 27." },
    { label: "Weapons", kind: "movie", icon: "film", note: "August 8." },
    { label: "Demon Slayer: Infinity Castle", kind: "movie", icon: "film", note: "September; the biggest anime film ever." },
    { label: "One Battle After Another", kind: "movie", icon: "film", note: "September 26." },
    { label: "Wicked: For Good and Zootopia 2", kind: "movie", icon: "film", note: "November." },
    { label: "Avatar: Fire and Ash", kind: "movie", icon: "film", note: "December 19." },
    { label: "Stranger Things 5", kind: "show", icon: "stream", note: "November 26, December 25, and a New Year's Eve finale." },
    { label: "Adolescence", kind: "show", icon: "stream", note: "March." },
    { label: "Severance season 2 and The Pitt", kind: "show", icon: "tv", note: "January." },
    { label: "The White Lotus season 3 and The Studio", kind: "show", icon: "tv" },
    { label: "Andor season 2 and The Last of Us season 2", kind: "show", icon: "stream", note: "April." },
    { label: "Squid Game season 3", kind: "show", icon: "stream", note: "June 27." },
    { label: "Wednesday season 2 and Alien: Earth", kind: "show", icon: "stream", note: "August." },
    { label: "Pluribus and Fallout season 2", kind: "show", icon: "tv", note: "November and December." },
    { label: "Heated Rivalry", kind: "show", icon: "tv", note: "November 28." },
  ],
  music: [
    { id: "c2025-golden", title: "Golden", artist: "HUNTR/X (KPop Demon Hunters)" },
    { id: "c2025-ordinary", title: "Ordinary", artist: "Alex Warren" },
    { id: "c2025-luther", title: "luther", artist: "Kendrick Lamar & SZA" },
    { id: "c2025-diewithasmile", title: "Die With a Smile", artist: "Lady Gaga & Bruno Mars" },
    { id: "c2025-apt", title: "APT.", artist: "ROSÉ & Bruno Mars" },
    { id: "c2025-manchild", title: "Manchild", artist: "Sabrina Carpenter" },
    { id: "c2025-fateofophelia", title: "The Fate of Ophelia", artist: "Taylor Swift" },
    { id: "c2025-dtmf", title: "DtMF", artist: "Bad Bunny" },
    { id: "c2025-anxiety", title: "Anxiety", artist: "Doechii" },
    { id: "c2025-abracadabra", title: "Abracadabra", artist: "Lady Gaga" },
    { id: "c2025-messy", title: "Messy", artist: "Lola Young" },
    { id: "c2025-pinkponyclub", title: "Pink Pony Club", artist: "Chappell Roan" },
    { id: "c2025-backtofriends", title: "back to friends", artist: "sombr" },
    { id: "c2025-nokia", title: "Nokia", artist: "Drake" },
    { id: "c2025-daisies", title: "Daisies", artist: "Justin Bieber" },
    { id: "c2025-whatiwant", title: "What I Want", artist: "Morgan Wallen ft. Tate McRae" },
  ],
  culture: [
    { label: "Eagles win the Super Bowl; Kendrick's halftime", kind: "event", icon: "trophy", note: "February 9." },
    { label: "Labubu", kind: "toy", icon: "toy", note: "The keychain monster of the year." },
    { label: "Dubai chocolate and matcha", kind: "food", icon: "pizza" },
    { label: "Taylor Swift and Travis Kelce get engaged", kind: "event", icon: "heart", note: "August 26; The Life of a Showgirl followed October 3." },
    { label: "Oasis reunites; Black Sabbath's farewell", kind: "event", icon: "music", note: "July." },
    { label: "Los Angeles wildfires", kind: "event", icon: "sun", note: "January." },
    { label: "The longest government shutdown", kind: "event", icon: "flag", note: "October 1–November 12." },
    { label: "Dodgers repeat; Thunder win the NBA Finals", kind: "event", icon: "ball" },
    { label: "Sinner vs. Alcaraz", kind: "sport", icon: "ball", note: "Four Grand Slam finals, split two each." },
    { label: "Rory McIlroy completes the career Grand Slam", kind: "sport", icon: "ball", note: "April 13." },
    { label: "Sambas, baggy jeans, and boxers as shorts", kind: "fashion", icon: "star" },
    { label: "\"Huzz\", \"chopped\", \"sybau\", \"type shit\"", kind: "slang", icon: "smile" },
    { label: "Bad Bunny's Puerto Rico residency", kind: "event", icon: "music", note: "July–September; Super Bowl LX halftime announced in September." },
  ],
  capsule: [
    { label: "Switch 2", icon: "switch" },
    { label: "Labubu", icon: "toy" },
    { label: "Liquid Glass", icon: "iphone" },
    { label: "Tiger Rumi", icon: "sparkle" },
    { label: "Silksong needle", icon: "bug" },
    { label: "Six-seven hands", icon: "smile" },
  ],
};
